"""Markdown renderer for a roadmap version — the shareable, repo-committable plan document."""

from __future__ import annotations

import uuid

from shire.domain.repository.models import RepositoryRow
from shire.domain.roadmap.models import (
    RoadmapItemRow,
    RoadmapMilestoneRow,
    RoadmapRow,
    RoadmapVersionRow,
)
from shire.domain.roadmap.schemas import quadrant_of

_QUADRANT_LABELS = {
    "do_first": "Do first",
    "schedule": "Schedule",
    "delegate": "Quick win",
    "later": "Later",
}

_CHECKBOX = {"done": "x"}


def render_markdown(
    roadmap: RoadmapRow,
    version: RoadmapVersionRow,
    milestones: list[RoadmapMilestoneRow],
    items: list[RoadmapItemRow],
    repos: dict[uuid.UUID, RepositoryRow],
) -> str:
    lines = [f"# {roadmap.name}", ""]
    lines.append(f"_Roadmap version {version.number}, generated by Shire._")
    lines.append("")
    if roadmap.goal:
        lines += ["## Goal", "", roadmap.goal.strip(), ""]

    if version.assessments:
        lines += ["## Repository assessment", ""]
        dimensions = sorted({dim for a in version.assessments for dim in (a.get("scores") or {})})
        header = "| Repository | " + " | ".join(d.replace("_", " ") for d in dimensions) + " |"
        lines.append(header)
        lines.append("|" + " --- |" * (len(dimensions) + 1))
        for assessment in version.assessments:
            scores = assessment.get("scores") or {}
            cells = " | ".join(str(scores.get(d, "—")) for d in dimensions)
            lines.append(f"| {assessment.get('repo') or '(portfolio)'} | {cells} |")
        lines.append("")

    by_milestone: dict[uuid.UUID | None, list[RoadmapItemRow]] = {}
    for item in items:
        by_milestone.setdefault(item.milestone_id, []).append(item)

    for index, milestone in enumerate(milestones, start=1):
        lines.append(f"## M{index} — {milestone.title}")
        lines.append("")
        if milestone.summary:
            lines += [milestone.summary.strip(), ""]
        for item in by_milestone.get(milestone.id, []):
            lines += _item_lines(item, repos)
        lines.append("")

    carried = by_milestone.get(None, [])
    if carried:
        lines += ["## Carried over", ""]
        for item in carried:
            lines += _item_lines(item, repos)
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _item_lines(item: RoadmapItemRow, repos: dict[uuid.UUID, RepositoryRow]) -> list[str]:
    check = _CHECKBOX.get(item.status, " ")
    quadrant = _QUADRANT_LABELS[quadrant_of(urgent=item.urgent, important=item.important)]
    repo = repos.get(item.repository_id) if item.repository_id else None
    scope = f"`{repo.owner}/{repo.name}`" if repo else "_portfolio-wide_"
    chips = f"[{item.label}] ({quadrant}" + (f", {item.effort}" if item.effort else "") + ")"
    lines = [f"- [{check}] **{item.title}** — {scope} {chips}"]
    if item.description:
        lines.append(f"  - {item.description.strip()}")
    if item.rationale:
        lines.append(f"  - _Why:_ {item.rationale.strip()}")
    if item.issue_url:
        lines.append(f"  - Issue: {item.issue_url}")
    return lines
