/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as MembersRouteImport } from './routes/members'
import { Route as HobitsRouteImport } from './routes/hobits'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HobitsIndexRouteImport } from './routes/hobits.index'
import { Route as RepositoriesIdRouteImport } from './routes/repositories.$id'
import { Route as HobitsSlugRouteImport } from './routes/hobits.$slug'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const HobitsRoute = HobitsRouteImport.update({
  id: '/hobits',
  path: '/hobits',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HobitsIndexRoute = HobitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HobitsRoute,
} as any)
const RepositoriesIdRoute = RepositoriesIdRouteImport.update({
  id: '/repositories/$id',
  path: '/repositories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HobitsSlugRoute = HobitsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HobitsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRoute
  '/feed': typeof FeedRoute
  '/hobits': typeof HobitsRouteWithChildren
  '/members': typeof MembersRoute
  '/tools': typeof ToolsRoute
  '/hobits/$slug': typeof HobitsSlugRoute
  '/repositories/$id': typeof RepositoriesIdRoute
  '/hobits/': typeof HobitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRoute
  '/feed': typeof FeedRoute
  '/members': typeof MembersRoute
  '/tools': typeof ToolsRoute
  '/hobits/$slug': typeof HobitsSlugRoute
  '/repositories/$id': typeof RepositoriesIdRoute
  '/hobits': typeof HobitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRoute
  '/feed': typeof FeedRoute
  '/hobits': typeof HobitsRouteWithChildren
  '/members': typeof MembersRoute
  '/tools': typeof ToolsRoute
  '/hobits/$slug': typeof HobitsSlugRoute
  '/repositories/$id': typeof RepositoriesIdRoute
  '/hobits/': typeof HobitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connectors'
    | '/feed'
    | '/hobits'
    | '/members'
    | '/tools'
    | '/hobits/$slug'
    | '/repositories/$id'
    | '/hobits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connectors'
    | '/feed'
    | '/members'
    | '/tools'
    | '/hobits/$slug'
    | '/repositories/$id'
    | '/hobits'
  id:
    | '__root__'
    | '/'
    | '/connectors'
    | '/feed'
    | '/hobits'
    | '/members'
    | '/tools'
    | '/hobits/$slug'
    | '/repositories/$id'
    | '/hobits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectorsRoute: typeof ConnectorsRoute
  FeedRoute: typeof FeedRoute
  HobitsRoute: typeof HobitsRouteWithChildren
  MembersRoute: typeof MembersRoute
  ToolsRoute: typeof ToolsRoute
  RepositoriesIdRoute: typeof RepositoriesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hobits': {
      id: '/hobits'
      path: '/hobits'
      fullPath: '/hobits'
      preLoaderRoute: typeof HobitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hobits/': {
      id: '/hobits/'
      path: '/'
      fullPath: '/hobits/'
      preLoaderRoute: typeof HobitsIndexRouteImport
      parentRoute: typeof HobitsRoute
    }
    '/repositories/$id': {
      id: '/repositories/$id'
      path: '/repositories/$id'
      fullPath: '/repositories/$id'
      preLoaderRoute: typeof RepositoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hobits/$slug': {
      id: '/hobits/$slug'
      path: '/$slug'
      fullPath: '/hobits/$slug'
      preLoaderRoute: typeof HobitsSlugRouteImport
      parentRoute: typeof HobitsRoute
    }
  }
}

interface HobitsRouteChildren {
  HobitsSlugRoute: typeof HobitsSlugRoute
  HobitsIndexRoute: typeof HobitsIndexRoute
}

const HobitsRouteChildren: HobitsRouteChildren = {
  HobitsSlugRoute: HobitsSlugRoute,
  HobitsIndexRoute: HobitsIndexRoute,
}

const HobitsRouteWithChildren =
  HobitsRoute._addFileChildren(HobitsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectorsRoute: ConnectorsRoute,
  FeedRoute: FeedRoute,
  HobitsRoute: HobitsRouteWithChildren,
  MembersRoute: MembersRoute,
  ToolsRoute: ToolsRoute,
  RepositoriesIdRoute: RepositoriesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
