/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TechnologiesRouteImport } from './routes/technologies'
import { Route as TechChooserRouteImport } from './routes/tech-chooser'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RoadmapsRouteImport } from './routes/roadmaps'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as QualitiesRouteImport } from './routes/qualities'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as PrinciplesRouteImport } from './routes/principles'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MergeReviewsRouteImport } from './routes/merge-reviews'
import { Route as MembersRouteImport } from './routes/members'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as HobitsRouteImport } from './routes/hobits'
import { Route as HighlightsRouteImport } from './routes/highlights'
import { Route as DevelopmentsRouteImport } from './routes/developments'
import { Route as DataRouteImport } from './routes/data'
import { Route as CouncilRouteImport } from './routes/council'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CapacityPlannerRouteImport } from './routes/capacity-planner'
import { Route as ArchitecturesRouteImport } from './routes/architectures'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AiReadinessRouteImport } from './routes/ai-readiness'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechnologiesIndexRouteImport } from './routes/technologies/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SecurityIndexRouteImport } from './routes/security/index'
import { Route as RoadmapsIndexRouteImport } from './routes/roadmaps.index'
import { Route as RepositoriesIndexRouteImport } from './routes/repositories.index'
import { Route as QualitiesIndexRouteImport } from './routes/qualities/index'
import { Route as PromptsIndexRouteImport } from './routes/prompts/index'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as HobitsIndexRouteImport } from './routes/hobits.index'
import { Route as DataIndexRouteImport } from './routes/data/index'
import { Route as CouncilIndexRouteImport } from './routes/council.index'
import { Route as ArchitecturesIndexRouteImport } from './routes/architectures/index'
import { Route as TechnologiesNewRouteImport } from './routes/technologies/new'
import { Route as TechnologiesCompareRouteImport } from './routes/technologies/compare'
import { Route as RoadmapsNewRouteImport } from './routes/roadmaps.new'
import { Route as RoadmapsIdRouteImport } from './routes/roadmaps.$id'
import { Route as RepositoriesIdRouteImport } from './routes/repositories.$id'
import { Route as QualitiesIdRouteImport } from './routes/qualities/$id'
import { Route as PromptsNewRouteImport } from './routes/prompts/new'
import { Route as PromptsIdRouteImport } from './routes/prompts/$id'
import { Route as MergeReviewsIdRouteImport } from './routes/merge-reviews.$id'
import { Route as MembersCompareRouteImport } from './routes/members/compare'
import { Route as MembersIdRouteImport } from './routes/members/$id'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as HobitsSlugRouteImport } from './routes/hobits.$slug'
import { Route as DataNewRouteImport } from './routes/data/new'
import { Route as DataCompareRouteImport } from './routes/data/compare'
import { Route as CouncilNewRouteImport } from './routes/council.new'
import { Route as CouncilIdRouteImport } from './routes/council.$id'
import { Route as ArchitecturesNewRouteImport } from './routes/architectures/new'
import { Route as ArchitecturesCompareRouteImport } from './routes/architectures/compare'
import { Route as ArchitecturesAdvisorRouteImport } from './routes/architectures/advisor'
import { Route as TechnologiesIdIndexRouteImport } from './routes/technologies/$id/index'
import { Route as DataIdIndexRouteImport } from './routes/data/$id/index'
import { Route as ArchitecturesIdIndexRouteImport } from './routes/architectures/$id/index'
import { Route as TechnologiesIdEditRouteImport } from './routes/technologies/$id/edit'
import { Route as SecurityRegulationsIdRouteImport } from './routes/security/regulations/$id'
import { Route as SecurityPracticesIdRouteImport } from './routes/security/practices/$id'
import { Route as DiagramRepoIdKindRouteImport } from './routes/diagram.$repoId.$kind'
import { Route as DataIdEditRouteImport } from './routes/data/$id/edit'
import { Route as ArchitecturesIdEditRouteImport } from './routes/architectures/$id/edit'
import { Route as ArchitecturesIdDiagramRouteImport } from './routes/architectures/$id/diagram'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologiesRoute = TechnologiesRouteImport.update({
  id: '/technologies',
  path: '/technologies',
  getParentRoute: () => rootRouteImport,
} as any)
const TechChooserRoute = TechChooserRouteImport.update({
  id: '/tech-chooser',
  path: '/tech-chooser',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsRoute = RoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const QualitiesRoute = QualitiesRouteImport.update({
  id: '/qualities',
  path: '/qualities',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const PrinciplesRoute = PrinciplesRouteImport.update({
  id: '/principles',
  path: '/principles',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MergeReviewsRoute = MergeReviewsRouteImport.update({
  id: '/merge-reviews',
  path: '/merge-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HobitsRoute = HobitsRouteImport.update({
  id: '/hobits',
  path: '/hobits',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightsRoute = HighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentsRoute = DevelopmentsRouteImport.update({
  id: '/developments',
  path: '/developments',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const CouncilRoute = CouncilRouteImport.update({
  id: '/council',
  path: '/council',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacityPlannerRoute = CapacityPlannerRouteImport.update({
  id: '/capacity-planner',
  path: '/capacity-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitecturesRoute = ArchitecturesRouteImport.update({
  id: '/architectures',
  path: '/architectures',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AiReadinessRoute = AiReadinessRouteImport.update({
  id: '/ai-readiness',
  path: '/ai-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologiesIndexRoute = TechnologiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TechnologiesRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SecurityIndexRoute = SecurityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecurityRoute,
} as any)
const RoadmapsIndexRoute = RoadmapsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoadmapsRoute,
} as any)
const RepositoriesIndexRoute = RepositoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepositoriesRoute,
} as any)
const QualitiesIndexRoute = QualitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QualitiesRoute,
} as any)
const PromptsIndexRoute = PromptsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PromptsRoute,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembersRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const HobitsIndexRoute = HobitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HobitsRoute,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DataRoute,
} as any)
const CouncilIndexRoute = CouncilIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CouncilRoute,
} as any)
const ArchitecturesIndexRoute = ArchitecturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArchitecturesRoute,
} as any)
const TechnologiesNewRoute = TechnologiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TechnologiesRoute,
} as any)
const TechnologiesCompareRoute = TechnologiesCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => TechnologiesRoute,
} as any)
const RoadmapsNewRoute = RoadmapsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RoadmapsRoute,
} as any)
const RoadmapsIdRoute = RoadmapsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RoadmapsRoute,
} as any)
const RepositoriesIdRoute = RepositoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RepositoriesRoute,
} as any)
const QualitiesIdRoute = QualitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => QualitiesRoute,
} as any)
const PromptsNewRoute = PromptsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PromptsRoute,
} as any)
const PromptsIdRoute = PromptsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PromptsRoute,
} as any)
const MergeReviewsIdRoute = MergeReviewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MergeReviewsRoute,
} as any)
const MembersCompareRoute = MembersCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => MembersRoute,
} as any)
const MembersIdRoute = MembersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MembersRoute,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JobsRoute,
} as any)
const HobitsSlugRoute = HobitsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HobitsRoute,
} as any)
const DataNewRoute = DataNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DataRoute,
} as any)
const DataCompareRoute = DataCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => DataRoute,
} as any)
const CouncilNewRoute = CouncilNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CouncilRoute,
} as any)
const CouncilIdRoute = CouncilIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CouncilRoute,
} as any)
const ArchitecturesNewRoute = ArchitecturesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ArchitecturesRoute,
} as any)
const ArchitecturesCompareRoute = ArchitecturesCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => ArchitecturesRoute,
} as any)
const ArchitecturesAdvisorRoute = ArchitecturesAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => ArchitecturesRoute,
} as any)
const TechnologiesIdIndexRoute = TechnologiesIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => TechnologiesRoute,
} as any)
const DataIdIndexRoute = DataIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => DataRoute,
} as any)
const ArchitecturesIdIndexRoute = ArchitecturesIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => ArchitecturesRoute,
} as any)
const TechnologiesIdEditRoute = TechnologiesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => TechnologiesRoute,
} as any)
const SecurityRegulationsIdRoute = SecurityRegulationsIdRouteImport.update({
  id: '/regulations/$id',
  path: '/regulations/$id',
  getParentRoute: () => SecurityRoute,
} as any)
const SecurityPracticesIdRoute = SecurityPracticesIdRouteImport.update({
  id: '/practices/$id',
  path: '/practices/$id',
  getParentRoute: () => SecurityRoute,
} as any)
const DiagramRepoIdKindRoute = DiagramRepoIdKindRouteImport.update({
  id: '/diagram/$repoId/$kind',
  path: '/diagram/$repoId/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIdEditRoute = DataIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => DataRoute,
} as any)
const ArchitecturesIdEditRoute = ArchitecturesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => ArchitecturesRoute,
} as any)
const ArchitecturesIdDiagramRoute = ArchitecturesIdDiagramRouteImport.update({
  id: '/$id/diagram',
  path: '/$id/diagram',
  getParentRoute: () => ArchitecturesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-readiness': typeof AiReadinessRoute
  '/apps': typeof AppsRoute
  '/architectures': typeof ArchitecturesRouteWithChildren
  '/capacity-planner': typeof CapacityPlannerRoute
  '/compliance': typeof ComplianceRoute
  '/connectors': typeof ConnectorsRoute
  '/council': typeof CouncilRouteWithChildren
  '/data': typeof DataRouteWithChildren
  '/developments': typeof DevelopmentsRoute
  '/highlights': typeof HighlightsRoute
  '/hobits': typeof HobitsRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/members': typeof MembersRouteWithChildren
  '/merge-reviews': typeof MergeReviewsRouteWithChildren
  '/news': typeof NewsRoute
  '/principles': typeof PrinciplesRoute
  '/prompts': typeof PromptsRouteWithChildren
  '/qualities': typeof QualitiesRouteWithChildren
  '/repositories': typeof RepositoriesRouteWithChildren
  '/roadmaps': typeof RoadmapsRouteWithChildren
  '/security': typeof SecurityRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/tech-chooser': typeof TechChooserRoute
  '/technologies': typeof TechnologiesRouteWithChildren
  '/tools': typeof ToolsRoute
  '/architectures/advisor': typeof ArchitecturesAdvisorRoute
  '/architectures/compare': typeof ArchitecturesCompareRoute
  '/architectures/new': typeof ArchitecturesNewRoute
  '/council/$id': typeof CouncilIdRoute
  '/council/new': typeof CouncilNewRoute
  '/data/compare': typeof DataCompareRoute
  '/data/new': typeof DataNewRoute
  '/hobits/$slug': typeof HobitsSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/members/$id': typeof MembersIdRoute
  '/members/compare': typeof MembersCompareRoute
  '/merge-reviews/$id': typeof MergeReviewsIdRoute
  '/prompts/$id': typeof PromptsIdRoute
  '/prompts/new': typeof PromptsNewRoute
  '/qualities/$id': typeof QualitiesIdRoute
  '/repositories/$id': typeof RepositoriesIdRoute
  '/roadmaps/$id': typeof RoadmapsIdRoute
  '/roadmaps/new': typeof RoadmapsNewRoute
  '/technologies/compare': typeof TechnologiesCompareRoute
  '/technologies/new': typeof TechnologiesNewRoute
  '/architectures/': typeof ArchitecturesIndexRoute
  '/council/': typeof CouncilIndexRoute
  '/data/': typeof DataIndexRoute
  '/hobits/': typeof HobitsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/prompts/': typeof PromptsIndexRoute
  '/qualities/': typeof QualitiesIndexRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/roadmaps/': typeof RoadmapsIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/technologies/': typeof TechnologiesIndexRoute
  '/architectures/$id/diagram': typeof ArchitecturesIdDiagramRoute
  '/architectures/$id/edit': typeof ArchitecturesIdEditRoute
  '/data/$id/edit': typeof DataIdEditRoute
  '/diagram/$repoId/$kind': typeof DiagramRepoIdKindRoute
  '/security/practices/$id': typeof SecurityPracticesIdRoute
  '/security/regulations/$id': typeof SecurityRegulationsIdRoute
  '/technologies/$id/edit': typeof TechnologiesIdEditRoute
  '/architectures/$id/': typeof ArchitecturesIdIndexRoute
  '/data/$id/': typeof DataIdIndexRoute
  '/technologies/$id/': typeof TechnologiesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-readiness': typeof AiReadinessRoute
  '/apps': typeof AppsRoute
  '/capacity-planner': typeof CapacityPlannerRoute
  '/compliance': typeof ComplianceRoute
  '/connectors': typeof ConnectorsRoute
  '/developments': typeof DevelopmentsRoute
  '/highlights': typeof HighlightsRoute
  '/merge-reviews': typeof MergeReviewsRouteWithChildren
  '/news': typeof NewsRoute
  '/principles': typeof PrinciplesRoute
  '/tech-chooser': typeof TechChooserRoute
  '/tools': typeof ToolsRoute
  '/architectures/advisor': typeof ArchitecturesAdvisorRoute
  '/architectures/compare': typeof ArchitecturesCompareRoute
  '/architectures/new': typeof ArchitecturesNewRoute
  '/council/$id': typeof CouncilIdRoute
  '/council/new': typeof CouncilNewRoute
  '/data/compare': typeof DataCompareRoute
  '/data/new': typeof DataNewRoute
  '/hobits/$slug': typeof HobitsSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/members/$id': typeof MembersIdRoute
  '/members/compare': typeof MembersCompareRoute
  '/merge-reviews/$id': typeof MergeReviewsIdRoute
  '/prompts/$id': typeof PromptsIdRoute
  '/prompts/new': typeof PromptsNewRoute
  '/qualities/$id': typeof QualitiesIdRoute
  '/repositories/$id': typeof RepositoriesIdRoute
  '/roadmaps/$id': typeof RoadmapsIdRoute
  '/roadmaps/new': typeof RoadmapsNewRoute
  '/technologies/compare': typeof TechnologiesCompareRoute
  '/technologies/new': typeof TechnologiesNewRoute
  '/architectures': typeof ArchitecturesIndexRoute
  '/council': typeof CouncilIndexRoute
  '/data': typeof DataIndexRoute
  '/hobits': typeof HobitsIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/members': typeof MembersIndexRoute
  '/prompts': typeof PromptsIndexRoute
  '/qualities': typeof QualitiesIndexRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/roadmaps': typeof RoadmapsIndexRoute
  '/security': typeof SecurityIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/technologies': typeof TechnologiesIndexRoute
  '/architectures/$id/diagram': typeof ArchitecturesIdDiagramRoute
  '/architectures/$id/edit': typeof ArchitecturesIdEditRoute
  '/data/$id/edit': typeof DataIdEditRoute
  '/diagram/$repoId/$kind': typeof DiagramRepoIdKindRoute
  '/security/practices/$id': typeof SecurityPracticesIdRoute
  '/security/regulations/$id': typeof SecurityRegulationsIdRoute
  '/technologies/$id/edit': typeof TechnologiesIdEditRoute
  '/architectures/$id': typeof ArchitecturesIdIndexRoute
  '/data/$id': typeof DataIdIndexRoute
  '/technologies/$id': typeof TechnologiesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-readiness': typeof AiReadinessRoute
  '/apps': typeof AppsRoute
  '/architectures': typeof ArchitecturesRouteWithChildren
  '/capacity-planner': typeof CapacityPlannerRoute
  '/compliance': typeof ComplianceRoute
  '/connectors': typeof ConnectorsRoute
  '/council': typeof CouncilRouteWithChildren
  '/data': typeof DataRouteWithChildren
  '/developments': typeof DevelopmentsRoute
  '/highlights': typeof HighlightsRoute
  '/hobits': typeof HobitsRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/members': typeof MembersRouteWithChildren
  '/merge-reviews': typeof MergeReviewsRouteWithChildren
  '/news': typeof NewsRoute
  '/principles': typeof PrinciplesRoute
  '/prompts': typeof PromptsRouteWithChildren
  '/qualities': typeof QualitiesRouteWithChildren
  '/repositories': typeof RepositoriesRouteWithChildren
  '/roadmaps': typeof RoadmapsRouteWithChildren
  '/security': typeof SecurityRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/tech-chooser': typeof TechChooserRoute
  '/technologies': typeof TechnologiesRouteWithChildren
  '/tools': typeof ToolsRoute
  '/architectures/advisor': typeof ArchitecturesAdvisorRoute
  '/architectures/compare': typeof ArchitecturesCompareRoute
  '/architectures/new': typeof ArchitecturesNewRoute
  '/council/$id': typeof CouncilIdRoute
  '/council/new': typeof CouncilNewRoute
  '/data/compare': typeof DataCompareRoute
  '/data/new': typeof DataNewRoute
  '/hobits/$slug': typeof HobitsSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/members/$id': typeof MembersIdRoute
  '/members/compare': typeof MembersCompareRoute
  '/merge-reviews/$id': typeof MergeReviewsIdRoute
  '/prompts/$id': typeof PromptsIdRoute
  '/prompts/new': typeof PromptsNewRoute
  '/qualities/$id': typeof QualitiesIdRoute
  '/repositories/$id': typeof RepositoriesIdRoute
  '/roadmaps/$id': typeof RoadmapsIdRoute
  '/roadmaps/new': typeof RoadmapsNewRoute
  '/technologies/compare': typeof TechnologiesCompareRoute
  '/technologies/new': typeof TechnologiesNewRoute
  '/architectures/': typeof ArchitecturesIndexRoute
  '/council/': typeof CouncilIndexRoute
  '/data/': typeof DataIndexRoute
  '/hobits/': typeof HobitsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/prompts/': typeof PromptsIndexRoute
  '/qualities/': typeof QualitiesIndexRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/roadmaps/': typeof RoadmapsIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/technologies/': typeof TechnologiesIndexRoute
  '/architectures/$id/diagram': typeof ArchitecturesIdDiagramRoute
  '/architectures/$id/edit': typeof ArchitecturesIdEditRoute
  '/data/$id/edit': typeof DataIdEditRoute
  '/diagram/$repoId/$kind': typeof DiagramRepoIdKindRoute
  '/security/practices/$id': typeof SecurityPracticesIdRoute
  '/security/regulations/$id': typeof SecurityRegulationsIdRoute
  '/technologies/$id/edit': typeof TechnologiesIdEditRoute
  '/architectures/$id/': typeof ArchitecturesIdIndexRoute
  '/data/$id/': typeof DataIdIndexRoute
  '/technologies/$id/': typeof TechnologiesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-readiness'
    | '/apps'
    | '/architectures'
    | '/capacity-planner'
    | '/compliance'
    | '/connectors'
    | '/council'
    | '/data'
    | '/developments'
    | '/highlights'
    | '/hobits'
    | '/jobs'
    | '/members'
    | '/merge-reviews'
    | '/news'
    | '/principles'
    | '/prompts'
    | '/qualities'
    | '/repositories'
    | '/roadmaps'
    | '/security'
    | '/settings'
    | '/tech-chooser'
    | '/technologies'
    | '/tools'
    | '/architectures/advisor'
    | '/architectures/compare'
    | '/architectures/new'
    | '/council/$id'
    | '/council/new'
    | '/data/compare'
    | '/data/new'
    | '/hobits/$slug'
    | '/jobs/$id'
    | '/members/$id'
    | '/members/compare'
    | '/merge-reviews/$id'
    | '/prompts/$id'
    | '/prompts/new'
    | '/qualities/$id'
    | '/repositories/$id'
    | '/roadmaps/$id'
    | '/roadmaps/new'
    | '/technologies/compare'
    | '/technologies/new'
    | '/architectures/'
    | '/council/'
    | '/data/'
    | '/hobits/'
    | '/jobs/'
    | '/members/'
    | '/prompts/'
    | '/qualities/'
    | '/repositories/'
    | '/roadmaps/'
    | '/security/'
    | '/settings/'
    | '/technologies/'
    | '/architectures/$id/diagram'
    | '/architectures/$id/edit'
    | '/data/$id/edit'
    | '/diagram/$repoId/$kind'
    | '/security/practices/$id'
    | '/security/regulations/$id'
    | '/technologies/$id/edit'
    | '/architectures/$id/'
    | '/data/$id/'
    | '/technologies/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-readiness'
    | '/apps'
    | '/capacity-planner'
    | '/compliance'
    | '/connectors'
    | '/developments'
    | '/highlights'
    | '/merge-reviews'
    | '/news'
    | '/principles'
    | '/tech-chooser'
    | '/tools'
    | '/architectures/advisor'
    | '/architectures/compare'
    | '/architectures/new'
    | '/council/$id'
    | '/council/new'
    | '/data/compare'
    | '/data/new'
    | '/hobits/$slug'
    | '/jobs/$id'
    | '/members/$id'
    | '/members/compare'
    | '/merge-reviews/$id'
    | '/prompts/$id'
    | '/prompts/new'
    | '/qualities/$id'
    | '/repositories/$id'
    | '/roadmaps/$id'
    | '/roadmaps/new'
    | '/technologies/compare'
    | '/technologies/new'
    | '/architectures'
    | '/council'
    | '/data'
    | '/hobits'
    | '/jobs'
    | '/members'
    | '/prompts'
    | '/qualities'
    | '/repositories'
    | '/roadmaps'
    | '/security'
    | '/settings'
    | '/technologies'
    | '/architectures/$id/diagram'
    | '/architectures/$id/edit'
    | '/data/$id/edit'
    | '/diagram/$repoId/$kind'
    | '/security/practices/$id'
    | '/security/regulations/$id'
    | '/technologies/$id/edit'
    | '/architectures/$id'
    | '/data/$id'
    | '/technologies/$id'
  id:
    | '__root__'
    | '/'
    | '/ai-readiness'
    | '/apps'
    | '/architectures'
    | '/capacity-planner'
    | '/compliance'
    | '/connectors'
    | '/council'
    | '/data'
    | '/developments'
    | '/highlights'
    | '/hobits'
    | '/jobs'
    | '/members'
    | '/merge-reviews'
    | '/news'
    | '/principles'
    | '/prompts'
    | '/qualities'
    | '/repositories'
    | '/roadmaps'
    | '/security'
    | '/settings'
    | '/tech-chooser'
    | '/technologies'
    | '/tools'
    | '/architectures/advisor'
    | '/architectures/compare'
    | '/architectures/new'
    | '/council/$id'
    | '/council/new'
    | '/data/compare'
    | '/data/new'
    | '/hobits/$slug'
    | '/jobs/$id'
    | '/members/$id'
    | '/members/compare'
    | '/merge-reviews/$id'
    | '/prompts/$id'
    | '/prompts/new'
    | '/qualities/$id'
    | '/repositories/$id'
    | '/roadmaps/$id'
    | '/roadmaps/new'
    | '/technologies/compare'
    | '/technologies/new'
    | '/architectures/'
    | '/council/'
    | '/data/'
    | '/hobits/'
    | '/jobs/'
    | '/members/'
    | '/prompts/'
    | '/qualities/'
    | '/repositories/'
    | '/roadmaps/'
    | '/security/'
    | '/settings/'
    | '/technologies/'
    | '/architectures/$id/diagram'
    | '/architectures/$id/edit'
    | '/data/$id/edit'
    | '/diagram/$repoId/$kind'
    | '/security/practices/$id'
    | '/security/regulations/$id'
    | '/technologies/$id/edit'
    | '/architectures/$id/'
    | '/data/$id/'
    | '/technologies/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiReadinessRoute: typeof AiReadinessRoute
  AppsRoute: typeof AppsRoute
  ArchitecturesRoute: typeof ArchitecturesRouteWithChildren
  CapacityPlannerRoute: typeof CapacityPlannerRoute
  ComplianceRoute: typeof ComplianceRoute
  ConnectorsRoute: typeof ConnectorsRoute
  CouncilRoute: typeof CouncilRouteWithChildren
  DataRoute: typeof DataRouteWithChildren
  DevelopmentsRoute: typeof DevelopmentsRoute
  HighlightsRoute: typeof HighlightsRoute
  HobitsRoute: typeof HobitsRouteWithChildren
  JobsRoute: typeof JobsRouteWithChildren
  MembersRoute: typeof MembersRouteWithChildren
  MergeReviewsRoute: typeof MergeReviewsRouteWithChildren
  NewsRoute: typeof NewsRoute
  PrinciplesRoute: typeof PrinciplesRoute
  PromptsRoute: typeof PromptsRouteWithChildren
  QualitiesRoute: typeof QualitiesRouteWithChildren
  RepositoriesRoute: typeof RepositoriesRouteWithChildren
  RoadmapsRoute: typeof RoadmapsRouteWithChildren
  SecurityRoute: typeof SecurityRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  TechChooserRoute: typeof TechChooserRoute
  TechnologiesRoute: typeof TechnologiesRouteWithChildren
  ToolsRoute: typeof ToolsRoute
  DiagramRepoIdKindRoute: typeof DiagramRepoIdKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technologies': {
      id: '/technologies'
      path: '/technologies'
      fullPath: '/technologies'
      preLoaderRoute: typeof TechnologiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-chooser': {
      id: '/tech-chooser'
      path: '/tech-chooser'
      fullPath: '/tech-chooser'
      preLoaderRoute: typeof TechChooserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps': {
      id: '/roadmaps'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof RoadmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualities': {
      id: '/qualities'
      path: '/qualities'
      fullPath: '/qualities'
      preLoaderRoute: typeof QualitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principles': {
      id: '/principles'
      path: '/principles'
      fullPath: '/principles'
      preLoaderRoute: typeof PrinciplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge-reviews': {
      id: '/merge-reviews'
      path: '/merge-reviews'
      fullPath: '/merge-reviews'
      preLoaderRoute: typeof MergeReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hobits': {
      id: '/hobits'
      path: '/hobits'
      fullPath: '/hobits'
      preLoaderRoute: typeof HobitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlights': {
      id: '/highlights'
      path: '/highlights'
      fullPath: '/highlights'
      preLoaderRoute: typeof HighlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developments': {
      id: '/developments'
      path: '/developments'
      fullPath: '/developments'
      preLoaderRoute: typeof DevelopmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/council': {
      id: '/council'
      path: '/council'
      fullPath: '/council'
      preLoaderRoute: typeof CouncilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacity-planner': {
      id: '/capacity-planner'
      path: '/capacity-planner'
      fullPath: '/capacity-planner'
      preLoaderRoute: typeof CapacityPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architectures': {
      id: '/architectures'
      path: '/architectures'
      fullPath: '/architectures'
      preLoaderRoute: typeof ArchitecturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-readiness': {
      id: '/ai-readiness'
      path: '/ai-readiness'
      fullPath: '/ai-readiness'
      preLoaderRoute: typeof AiReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technologies/': {
      id: '/technologies/'
      path: '/'
      fullPath: '/technologies/'
      preLoaderRoute: typeof TechnologiesIndexRouteImport
      parentRoute: typeof TechnologiesRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/security/': {
      id: '/security/'
      path: '/'
      fullPath: '/security/'
      preLoaderRoute: typeof SecurityIndexRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/roadmaps/': {
      id: '/roadmaps/'
      path: '/'
      fullPath: '/roadmaps/'
      preLoaderRoute: typeof RoadmapsIndexRouteImport
      parentRoute: typeof RoadmapsRoute
    }
    '/repositories/': {
      id: '/repositories/'
      path: '/'
      fullPath: '/repositories/'
      preLoaderRoute: typeof RepositoriesIndexRouteImport
      parentRoute: typeof RepositoriesRoute
    }
    '/qualities/': {
      id: '/qualities/'
      path: '/'
      fullPath: '/qualities/'
      preLoaderRoute: typeof QualitiesIndexRouteImport
      parentRoute: typeof QualitiesRoute
    }
    '/prompts/': {
      id: '/prompts/'
      path: '/'
      fullPath: '/prompts/'
      preLoaderRoute: typeof PromptsIndexRouteImport
      parentRoute: typeof PromptsRoute
    }
    '/members/': {
      id: '/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof MembersRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/hobits/': {
      id: '/hobits/'
      path: '/'
      fullPath: '/hobits/'
      preLoaderRoute: typeof HobitsIndexRouteImport
      parentRoute: typeof HobitsRoute
    }
    '/data/': {
      id: '/data/'
      path: '/'
      fullPath: '/data/'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof DataRoute
    }
    '/council/': {
      id: '/council/'
      path: '/'
      fullPath: '/council/'
      preLoaderRoute: typeof CouncilIndexRouteImport
      parentRoute: typeof CouncilRoute
    }
    '/architectures/': {
      id: '/architectures/'
      path: '/'
      fullPath: '/architectures/'
      preLoaderRoute: typeof ArchitecturesIndexRouteImport
      parentRoute: typeof ArchitecturesRoute
    }
    '/technologies/new': {
      id: '/technologies/new'
      path: '/new'
      fullPath: '/technologies/new'
      preLoaderRoute: typeof TechnologiesNewRouteImport
      parentRoute: typeof TechnologiesRoute
    }
    '/technologies/compare': {
      id: '/technologies/compare'
      path: '/compare'
      fullPath: '/technologies/compare'
      preLoaderRoute: typeof TechnologiesCompareRouteImport
      parentRoute: typeof TechnologiesRoute
    }
    '/roadmaps/new': {
      id: '/roadmaps/new'
      path: '/new'
      fullPath: '/roadmaps/new'
      preLoaderRoute: typeof RoadmapsNewRouteImport
      parentRoute: typeof RoadmapsRoute
    }
    '/roadmaps/$id': {
      id: '/roadmaps/$id'
      path: '/$id'
      fullPath: '/roadmaps/$id'
      preLoaderRoute: typeof RoadmapsIdRouteImport
      parentRoute: typeof RoadmapsRoute
    }
    '/repositories/$id': {
      id: '/repositories/$id'
      path: '/$id'
      fullPath: '/repositories/$id'
      preLoaderRoute: typeof RepositoriesIdRouteImport
      parentRoute: typeof RepositoriesRoute
    }
    '/qualities/$id': {
      id: '/qualities/$id'
      path: '/$id'
      fullPath: '/qualities/$id'
      preLoaderRoute: typeof QualitiesIdRouteImport
      parentRoute: typeof QualitiesRoute
    }
    '/prompts/new': {
      id: '/prompts/new'
      path: '/new'
      fullPath: '/prompts/new'
      preLoaderRoute: typeof PromptsNewRouteImport
      parentRoute: typeof PromptsRoute
    }
    '/prompts/$id': {
      id: '/prompts/$id'
      path: '/$id'
      fullPath: '/prompts/$id'
      preLoaderRoute: typeof PromptsIdRouteImport
      parentRoute: typeof PromptsRoute
    }
    '/merge-reviews/$id': {
      id: '/merge-reviews/$id'
      path: '/$id'
      fullPath: '/merge-reviews/$id'
      preLoaderRoute: typeof MergeReviewsIdRouteImport
      parentRoute: typeof MergeReviewsRoute
    }
    '/members/compare': {
      id: '/members/compare'
      path: '/compare'
      fullPath: '/members/compare'
      preLoaderRoute: typeof MembersCompareRouteImport
      parentRoute: typeof MembersRoute
    }
    '/members/$id': {
      id: '/members/$id'
      path: '/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof MembersIdRouteImport
      parentRoute: typeof MembersRoute
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/hobits/$slug': {
      id: '/hobits/$slug'
      path: '/$slug'
      fullPath: '/hobits/$slug'
      preLoaderRoute: typeof HobitsSlugRouteImport
      parentRoute: typeof HobitsRoute
    }
    '/data/new': {
      id: '/data/new'
      path: '/new'
      fullPath: '/data/new'
      preLoaderRoute: typeof DataNewRouteImport
      parentRoute: typeof DataRoute
    }
    '/data/compare': {
      id: '/data/compare'
      path: '/compare'
      fullPath: '/data/compare'
      preLoaderRoute: typeof DataCompareRouteImport
      parentRoute: typeof DataRoute
    }
    '/council/new': {
      id: '/council/new'
      path: '/new'
      fullPath: '/council/new'
      preLoaderRoute: typeof CouncilNewRouteImport
      parentRoute: typeof CouncilRoute
    }
    '/council/$id': {
      id: '/council/$id'
      path: '/$id'
      fullPath: '/council/$id'
      preLoaderRoute: typeof CouncilIdRouteImport
      parentRoute: typeof CouncilRoute
    }
    '/architectures/new': {
      id: '/architectures/new'
      path: '/new'
      fullPath: '/architectures/new'
      preLoaderRoute: typeof ArchitecturesNewRouteImport
      parentRoute: typeof ArchitecturesRoute
    }
    '/architectures/compare': {
      id: '/architectures/compare'
      path: '/compare'
      fullPath: '/architectures/compare'
      preLoaderRoute: typeof ArchitecturesCompareRouteImport
      parentRoute: typeof ArchitecturesRoute
    }
    '/architectures/advisor': {
      id: '/architectures/advisor'
      path: '/advisor'
      fullPath: '/architectures/advisor'
      preLoaderRoute: typeof ArchitecturesAdvisorRouteImport
      parentRoute: typeof ArchitecturesRoute
    }
    '/technologies/$id/': {
      id: '/technologies/$id/'
      path: '/$id'
      fullPath: '/technologies/$id/'
      preLoaderRoute: typeof TechnologiesIdIndexRouteImport
      parentRoute: typeof TechnologiesRoute
    }
    '/data/$id/': {
      id: '/data/$id/'
      path: '/$id'
      fullPath: '/data/$id/'
      preLoaderRoute: typeof DataIdIndexRouteImport
      parentRoute: typeof DataRoute
    }
    '/architectures/$id/': {
      id: '/architectures/$id/'
      path: '/$id'
      fullPath: '/architectures/$id/'
      preLoaderRoute: typeof ArchitecturesIdIndexRouteImport
      parentRoute: typeof ArchitecturesRoute
    }
    '/technologies/$id/edit': {
      id: '/technologies/$id/edit'
      path: '/$id/edit'
      fullPath: '/technologies/$id/edit'
      preLoaderRoute: typeof TechnologiesIdEditRouteImport
      parentRoute: typeof TechnologiesRoute
    }
    '/security/regulations/$id': {
      id: '/security/regulations/$id'
      path: '/regulations/$id'
      fullPath: '/security/regulations/$id'
      preLoaderRoute: typeof SecurityRegulationsIdRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/security/practices/$id': {
      id: '/security/practices/$id'
      path: '/practices/$id'
      fullPath: '/security/practices/$id'
      preLoaderRoute: typeof SecurityPracticesIdRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/diagram/$repoId/$kind': {
      id: '/diagram/$repoId/$kind'
      path: '/diagram/$repoId/$kind'
      fullPath: '/diagram/$repoId/$kind'
      preLoaderRoute: typeof DiagramRepoIdKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/$id/edit': {
      id: '/data/$id/edit'
      path: '/$id/edit'
      fullPath: '/data/$id/edit'
      preLoaderRoute: typeof DataIdEditRouteImport
      parentRoute: typeof DataRoute
    }
    '/architectures/$id/edit': {
      id: '/architectures/$id/edit'
      path: '/$id/edit'
      fullPath: '/architectures/$id/edit'
      preLoaderRoute: typeof ArchitecturesIdEditRouteImport
      parentRoute: typeof ArchitecturesRoute
    }
    '/architectures/$id/diagram': {
      id: '/architectures/$id/diagram'
      path: '/$id/diagram'
      fullPath: '/architectures/$id/diagram'
      preLoaderRoute: typeof ArchitecturesIdDiagramRouteImport
      parentRoute: typeof ArchitecturesRoute
    }
  }
}

interface ArchitecturesRouteChildren {
  ArchitecturesAdvisorRoute: typeof ArchitecturesAdvisorRoute
  ArchitecturesCompareRoute: typeof ArchitecturesCompareRoute
  ArchitecturesNewRoute: typeof ArchitecturesNewRoute
  ArchitecturesIndexRoute: typeof ArchitecturesIndexRoute
  ArchitecturesIdDiagramRoute: typeof ArchitecturesIdDiagramRoute
  ArchitecturesIdEditRoute: typeof ArchitecturesIdEditRoute
  ArchitecturesIdIndexRoute: typeof ArchitecturesIdIndexRoute
}

const ArchitecturesRouteChildren: ArchitecturesRouteChildren = {
  ArchitecturesAdvisorRoute: ArchitecturesAdvisorRoute,
  ArchitecturesCompareRoute: ArchitecturesCompareRoute,
  ArchitecturesNewRoute: ArchitecturesNewRoute,
  ArchitecturesIndexRoute: ArchitecturesIndexRoute,
  ArchitecturesIdDiagramRoute: ArchitecturesIdDiagramRoute,
  ArchitecturesIdEditRoute: ArchitecturesIdEditRoute,
  ArchitecturesIdIndexRoute: ArchitecturesIdIndexRoute,
}

const ArchitecturesRouteWithChildren = ArchitecturesRoute._addFileChildren(
  ArchitecturesRouteChildren,
)

interface CouncilRouteChildren {
  CouncilIdRoute: typeof CouncilIdRoute
  CouncilNewRoute: typeof CouncilNewRoute
  CouncilIndexRoute: typeof CouncilIndexRoute
}

const CouncilRouteChildren: CouncilRouteChildren = {
  CouncilIdRoute: CouncilIdRoute,
  CouncilNewRoute: CouncilNewRoute,
  CouncilIndexRoute: CouncilIndexRoute,
}

const CouncilRouteWithChildren =
  CouncilRoute._addFileChildren(CouncilRouteChildren)

interface DataRouteChildren {
  DataCompareRoute: typeof DataCompareRoute
  DataNewRoute: typeof DataNewRoute
  DataIndexRoute: typeof DataIndexRoute
  DataIdEditRoute: typeof DataIdEditRoute
  DataIdIndexRoute: typeof DataIdIndexRoute
}

const DataRouteChildren: DataRouteChildren = {
  DataCompareRoute: DataCompareRoute,
  DataNewRoute: DataNewRoute,
  DataIndexRoute: DataIndexRoute,
  DataIdEditRoute: DataIdEditRoute,
  DataIdIndexRoute: DataIdIndexRoute,
}

const DataRouteWithChildren = DataRoute._addFileChildren(DataRouteChildren)

interface HobitsRouteChildren {
  HobitsSlugRoute: typeof HobitsSlugRoute
  HobitsIndexRoute: typeof HobitsIndexRoute
}

const HobitsRouteChildren: HobitsRouteChildren = {
  HobitsSlugRoute: HobitsSlugRoute,
  HobitsIndexRoute: HobitsIndexRoute,
}

const HobitsRouteWithChildren =
  HobitsRoute._addFileChildren(HobitsRouteChildren)

interface JobsRouteChildren {
  JobsIdRoute: typeof JobsIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsIdRoute: JobsIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface MembersRouteChildren {
  MembersIdRoute: typeof MembersIdRoute
  MembersCompareRoute: typeof MembersCompareRoute
  MembersIndexRoute: typeof MembersIndexRoute
}

const MembersRouteChildren: MembersRouteChildren = {
  MembersIdRoute: MembersIdRoute,
  MembersCompareRoute: MembersCompareRoute,
  MembersIndexRoute: MembersIndexRoute,
}

const MembersRouteWithChildren =
  MembersRoute._addFileChildren(MembersRouteChildren)

interface MergeReviewsRouteChildren {
  MergeReviewsIdRoute: typeof MergeReviewsIdRoute
}

const MergeReviewsRouteChildren: MergeReviewsRouteChildren = {
  MergeReviewsIdRoute: MergeReviewsIdRoute,
}

const MergeReviewsRouteWithChildren = MergeReviewsRoute._addFileChildren(
  MergeReviewsRouteChildren,
)

interface PromptsRouteChildren {
  PromptsIdRoute: typeof PromptsIdRoute
  PromptsNewRoute: typeof PromptsNewRoute
  PromptsIndexRoute: typeof PromptsIndexRoute
}

const PromptsRouteChildren: PromptsRouteChildren = {
  PromptsIdRoute: PromptsIdRoute,
  PromptsNewRoute: PromptsNewRoute,
  PromptsIndexRoute: PromptsIndexRoute,
}

const PromptsRouteWithChildren =
  PromptsRoute._addFileChildren(PromptsRouteChildren)

interface QualitiesRouteChildren {
  QualitiesIdRoute: typeof QualitiesIdRoute
  QualitiesIndexRoute: typeof QualitiesIndexRoute
}

const QualitiesRouteChildren: QualitiesRouteChildren = {
  QualitiesIdRoute: QualitiesIdRoute,
  QualitiesIndexRoute: QualitiesIndexRoute,
}

const QualitiesRouteWithChildren = QualitiesRoute._addFileChildren(
  QualitiesRouteChildren,
)

interface RepositoriesRouteChildren {
  RepositoriesIdRoute: typeof RepositoriesIdRoute
  RepositoriesIndexRoute: typeof RepositoriesIndexRoute
}

const RepositoriesRouteChildren: RepositoriesRouteChildren = {
  RepositoriesIdRoute: RepositoriesIdRoute,
  RepositoriesIndexRoute: RepositoriesIndexRoute,
}

const RepositoriesRouteWithChildren = RepositoriesRoute._addFileChildren(
  RepositoriesRouteChildren,
)

interface RoadmapsRouteChildren {
  RoadmapsIdRoute: typeof RoadmapsIdRoute
  RoadmapsNewRoute: typeof RoadmapsNewRoute
  RoadmapsIndexRoute: typeof RoadmapsIndexRoute
}

const RoadmapsRouteChildren: RoadmapsRouteChildren = {
  RoadmapsIdRoute: RoadmapsIdRoute,
  RoadmapsNewRoute: RoadmapsNewRoute,
  RoadmapsIndexRoute: RoadmapsIndexRoute,
}

const RoadmapsRouteWithChildren = RoadmapsRoute._addFileChildren(
  RoadmapsRouteChildren,
)

interface SecurityRouteChildren {
  SecurityIndexRoute: typeof SecurityIndexRoute
  SecurityPracticesIdRoute: typeof SecurityPracticesIdRoute
  SecurityRegulationsIdRoute: typeof SecurityRegulationsIdRoute
}

const SecurityRouteChildren: SecurityRouteChildren = {
  SecurityIndexRoute: SecurityIndexRoute,
  SecurityPracticesIdRoute: SecurityPracticesIdRoute,
  SecurityRegulationsIdRoute: SecurityRegulationsIdRoute,
}

const SecurityRouteWithChildren = SecurityRoute._addFileChildren(
  SecurityRouteChildren,
)

interface SettingsRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface TechnologiesRouteChildren {
  TechnologiesCompareRoute: typeof TechnologiesCompareRoute
  TechnologiesNewRoute: typeof TechnologiesNewRoute
  TechnologiesIndexRoute: typeof TechnologiesIndexRoute
  TechnologiesIdEditRoute: typeof TechnologiesIdEditRoute
  TechnologiesIdIndexRoute: typeof TechnologiesIdIndexRoute
}

const TechnologiesRouteChildren: TechnologiesRouteChildren = {
  TechnologiesCompareRoute: TechnologiesCompareRoute,
  TechnologiesNewRoute: TechnologiesNewRoute,
  TechnologiesIndexRoute: TechnologiesIndexRoute,
  TechnologiesIdEditRoute: TechnologiesIdEditRoute,
  TechnologiesIdIndexRoute: TechnologiesIdIndexRoute,
}

const TechnologiesRouteWithChildren = TechnologiesRoute._addFileChildren(
  TechnologiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiReadinessRoute: AiReadinessRoute,
  AppsRoute: AppsRoute,
  ArchitecturesRoute: ArchitecturesRouteWithChildren,
  CapacityPlannerRoute: CapacityPlannerRoute,
  ComplianceRoute: ComplianceRoute,
  ConnectorsRoute: ConnectorsRoute,
  CouncilRoute: CouncilRouteWithChildren,
  DataRoute: DataRouteWithChildren,
  DevelopmentsRoute: DevelopmentsRoute,
  HighlightsRoute: HighlightsRoute,
  HobitsRoute: HobitsRouteWithChildren,
  JobsRoute: JobsRouteWithChildren,
  MembersRoute: MembersRouteWithChildren,
  MergeReviewsRoute: MergeReviewsRouteWithChildren,
  NewsRoute: NewsRoute,
  PrinciplesRoute: PrinciplesRoute,
  PromptsRoute: PromptsRouteWithChildren,
  QualitiesRoute: QualitiesRouteWithChildren,
  RepositoriesRoute: RepositoriesRouteWithChildren,
  RoadmapsRoute: RoadmapsRouteWithChildren,
  SecurityRoute: SecurityRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  TechChooserRoute: TechChooserRoute,
  TechnologiesRoute: TechnologiesRouteWithChildren,
  ToolsRoute: ToolsRoute,
  DiagramRepoIdKindRoute: DiagramRepoIdKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
