/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Repositories */
        get: operations["list_repositories_api_v1_repositories_get"];
        put?: never;
        /**
         * Ingest Repository
         * @description Clone and analyze a repository from a git URL (blocking).
         */
        post: operations["ingest_repository_api_v1_repositories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Repository */
        get: operations["get_repository_api_v1_repositories__repository_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Repository
         * @description Pull the latest from the remote and re-run the full analysis.
         */
        post: operations["refresh_repository_api_v1_repositories__repository_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Analysis */
        get: operations["latest_analysis_api_v1_repositories__repository_id__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dependencies/{name}/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Repositories Using Dependency */
        get: operations["repositories_using_dependency_api_v1_dependencies__name__repositories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/tools/{tool}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Tool On Demand
         * @description Run a single external tool against the current clone and merge it into the analysis.
         */
        post: operations["run_tool_on_demand_api_v1_repositories__repository_id__tools__tool__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/tools/{tool}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tool Log
         * @description Raw findings log (lint/SAST/dead-code/secret locations) for the tool's latest run.
         */
        get: operations["tool_log_api_v1_repositories__repository_id__tools__tool__log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Linked Integrations
         * @description Tool-ids of the integrations linked to this repository (the analysis allow-list).
         */
        get: operations["linked_integrations_api_v1_repositories__repository_id__integrations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/integrations/{tool_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link Integration
         * @description Link an integration to a repository (enables it; runs on the next refresh or manual run).
         */
        post: operations["link_integration_api_v1_repositories__repository_id__integrations__tool_id__post"];
        /**
         * Unlink Integration
         * @description Unlink an integration and clear its contributed data from the analysis.
         */
        delete: operations["unlink_integration_api_v1_repositories__repository_id__integrations__tool_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Codebase Graph
         * @description Whether a codebase graph exists for this repository and the URL to view it.
         */
        get: operations["codebase_graph_api_v1_repositories__repository_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/graph/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Codebase Graph
         * @description (Re)generate the interactive codebase graph (emerge) for the current clone.
         */
        post: operations["generate_codebase_graph_api_v1_repositories__repository_id__graph_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/code-age": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Code Age
         * @description Code age / survival over time (git-of-theseus): whether generated + the SVG URL.
         */
        get: operations["code_age_api_v1_repositories__repository_id__code_age_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/code-age/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Code Age
         * @description (Re)generate the code-age stacked-area chart (git-of-theseus) for the current clone.
         */
        post: operations["generate_code_age_api_v1_repositories__repository_id__code_age_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/coupling": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Coupling
         * @description Temporal (change) coupling (code-maat): ranked pairs of files that change together.
         */
        get: operations["coupling_api_v1_repositories__repository_id__coupling_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/coupling/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Coupling
         * @description (Re)compute temporal coupling (code-maat) from the current clone's git history.
         */
        post: operations["generate_coupling_api_v1_repositories__repository_id__coupling_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/code-map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Code Map
         * @description Code-city map (CodeCharta): whether generated + the viewer URL to iframe.
         */
        get: operations["code_map_api_v1_repositories__repository_id__code_map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/code-map/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Code Map
         * @description (Re)generate the CodeCharta code-city map for the current clone.
         */
        post: operations["generate_code_map_api_v1_repositories__repository_id__code_map_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connections */
        get: operations["list_connections_api_v1_connections_get"];
        put?: never;
        /**
         * Create Connection
         * @description Store a named credential set for a git provider.
         */
        post: operations["create_connection_api_v1_connections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connections/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Connection
         * @description Validate unsaved credentials against the provider (used by the create/edit form).
         */
        post: operations["test_connection_api_v1_connections_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Connection */
        get: operations["get_connection_api_v1_connections__connection_id__get"];
        put?: never;
        post?: never;
        /** Delete Connection */
        delete: operations["delete_connection_api_v1_connections__connection_id__delete"];
        options?: never;
        head?: never;
        /** Update Connection */
        patch: operations["update_connection_api_v1_connections__connection_id__patch"];
        trace?: never;
    };
    "/api/v1/connections/{connection_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Existing Connection
         * @description Validate a stored connection's credentials against the provider.
         */
        post: operations["test_existing_connection_api_v1_connections__connection_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tools
         * @description The persisted tools catalog (availability + versions). Fast read; refresh via /tools/sync.
         */
        get: operations["list_tools_api_v1_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Tools
         * @description Re-probe the local environment for every tool and refresh the stored catalog.
         */
        post: operations["sync_tools_api_v1_tools_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Members Overview
         * @description Fleet-wide members overview: portfolio health + aggregated identities.
         *
         *     Pass `anonymize=true` to replace names/emails with stable pseudonyms for sharing.
         */
        get: operations["members_overview_api_v1_members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/exclusions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Exclusions
         * @description User-managed opt-out / bot patterns applied on top of the built-in bot filters.
         */
        get: operations["list_exclusions_api_v1_members_exclusions_get"];
        put?: never;
        /**
         * Add Exclusion
         * @description Exclude a member from every view (an email or a glob like `*[bot]*`).
         */
        post: operations["add_exclusion_api_v1_members_exclusions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/exclusions/{exclusion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Exclusion */
        delete: operations["remove_exclusion_api_v1_members_exclusions__exclusion_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{identity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Member Detail
         * @description One member's cross-repo breakdown (per-repo commits + churn).
         */
        get: operations["member_detail_api_v1_members__identity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResult */
        AnalysisResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Commit Sha */
            commit_sha: string;
            /**
             * Analyzed At
             * Format: date-time
             */
            analyzed_at: string;
            facts: components["schemas"]["FactsResult"];
            /** Contributors */
            contributors: components["schemas"]["Contributor"][];
            /** Commit Activity */
            commit_activity: components["schemas"]["DailyCommitCount"][];
            /** Languages */
            languages: components["schemas"]["LanguageStat"][];
            /** Dependencies */
            dependencies: components["schemas"]["Dependency"][];
            /** Cicd */
            cicd: components["schemas"]["CiCdConfig"][];
            /** Hotspots */
            hotspots: components["schemas"]["Hotspot"][];
            enrichment: components["schemas"]["Enrichment"];
            /** Vulnerabilities */
            vulnerabilities: components["schemas"]["Vulnerability"][];
            /** Health Checks */
            health_checks: components["schemas"]["HealthCheck"][];
            /** Tool Runs */
            tool_runs: components["schemas"]["ToolRun"][];
        };
        /**
         * AuthMethod
         * @enum {string}
         */
        AuthMethod: "token" | "basic";
        /** CiCdConfig */
        CiCdConfig: {
            system: components["schemas"]["CiCdSystem"];
            /** Config Files */
            config_files: string[];
        };
        /**
         * CiCdSystem
         * @enum {string}
         */
        CiCdSystem: "github_actions" | "gitlab_ci" | "circleci" | "jenkins" | "travis" | "azure_pipelines" | "drone" | "other";
        /** CodeAgeCohort */
        CodeAgeCohort: {
            /** Label */
            label: string;
            /** Lines */
            lines: number;
        };
        /**
         * CodeAgeResult
         * @description State of a repository's code-age artifact (git-of-theseus stacked-area SVG).
         *
         *     `url` points at the generated SVG (rendered as an image); `cohorts` is the surviving-lines
         *     breakdown per year as of the latest commit.
         */
        CodeAgeResult: {
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Generated */
            generated: boolean;
            /** Url */
            url?: string | null;
            /** Generated At */
            generated_at?: string | null;
            /**
             * Cohorts
             * @default []
             */
            cohorts: components["schemas"]["CodeAgeCohort"][];
            /**
             * Tool Available
             * @default false
             */
            tool_available: boolean;
        };
        /**
         * CodeMapResult
         * @description State of a repository's code-city map (CodeCharta).
         *
         *     `url` points at the CodeCharta browser viewer with the generated map loaded (iframe target).
         *     `viewer_available` is separate from `tool_available`: the analyzer (ccsh) and the viewer
         *     (codecharta-visualization) are installed independently.
         */
        CodeMapResult: {
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Generated */
            generated: boolean;
            /** Url */
            url?: string | null;
            /** Generated At */
            generated_at?: string | null;
            /** File Count */
            file_count?: number | null;
            /**
             * Tool Available
             * @default false
             */
            tool_available: boolean;
            /**
             * Viewer Available
             * @default false
             */
            viewer_available: boolean;
        };
        /**
         * ConnectionResult
         * @description Result schema — never carries the secret, only a redacted hint.
         */
        ConnectionResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Provider */
            provider: string;
            /** Auth Method */
            auth_method: string;
            /** Username */
            username: string | null;
            /** Base Url */
            base_url: string | null;
            /** Secret Hint */
            secret_hint: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** Contributor */
        Contributor: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Commits */
            commits: number;
            /**
             * Lines Added
             * @default 0
             */
            lines_added: number;
            /**
             * Lines Removed
             * @default 0
             */
            lines_removed: number;
            /**
             * Files Touched
             * @default 0
             */
            files_touched: number;
            /** First Commit At */
            first_commit_at?: string | null;
            /** Last Commit At */
            last_commit_at?: string | null;
        };
        /** CouplingPair */
        CouplingPair: {
            /** Entity */
            entity: string;
            /** Coupled */
            coupled: string;
            /** Degree */
            degree: number;
            /** Average Revs */
            average_revs: number;
        };
        /**
         * CouplingResult
         * @description State of a repository's temporal-coupling analysis (code-maat).
         *
         *     Data, not an artifact: `pairs` are files that historically change together, ranked by coupling
         *     degree. Computed on demand and cached to disk so `generated_at` reflects the last run.
         */
        CouplingResult: {
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Generated */
            generated: boolean;
            /** Generated At */
            generated_at?: string | null;
            /**
             * Pairs
             * @default []
             */
            pairs: components["schemas"]["CouplingPair"][];
            /**
             * Tool Available
             * @default false
             */
            tool_available: boolean;
        };
        /**
         * CreateConnection
         * @description Create input: a named credential set.
         */
        CreateConnection: {
            provider: components["schemas"]["GitProvider"];
            auth_method: components["schemas"]["AuthMethod"];
            /** Username */
            username?: string | null;
            /** Secret */
            secret?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Name */
            name: string;
        };
        /** CreateMemberExclusion */
        CreateMemberExclusion: {
            /** Pattern */
            pattern: string;
            /** Reason */
            reason?: string | null;
            /**
             * Is Bot
             * @default false
             */
            is_bot: boolean;
        };
        /** DailyCommitCount */
        DailyCommitCount: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Count */
            count: number;
        };
        /** Dependency */
        Dependency: {
            ecosystem: components["schemas"]["Ecosystem"];
            /** Name */
            name: string;
            /** Version */
            version?: string | null;
            /** Manifest File */
            manifest_file: string;
            /**
             * Is Dev
             * @default false
             */
            is_dev: boolean;
        };
        /** DependencyUsageResult */
        DependencyUsageResult: {
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Versions */
            versions: string[];
        };
        /**
         * Ecosystem
         * @enum {string}
         */
        Ecosystem: "pip" | "npm" | "cargo" | "go" | "maven" | "gem" | "composer" | "generic";
        /**
         * Enrichment
         * @description Scalar enrichment bundle embedded on an Analysis (all tool-sourced, best-effort).
         */
        Enrichment: {
            /** Code Lines */
            code_lines?: number | null;
            /** Complexity Total */
            complexity_total?: number | null;
            /** Cocomo Cost Usd */
            cocomo_cost_usd?: number | null;
            /** Schedule Months */
            schedule_months?: number | null;
            /** Ccn Average */
            ccn_average?: number | null;
            /** Ccn Max */
            ccn_max?: number | null;
            /** Function Count */
            function_count?: number | null;
            /** High Complexity Count */
            high_complexity_count?: number | null;
            /** Maintainability Index */
            maintainability_index?: number | null;
            /** Sbom Package Count */
            sbom_package_count?: number | null;
            /**
             * Vulnerability Count
             * @default 0
             */
            vulnerability_count: number;
            /**
             * Vuln Critical
             * @default 0
             */
            vuln_critical: number;
            /**
             * Vuln High
             * @default 0
             */
            vuln_high: number;
            /**
             * Vuln Moderate
             * @default 0
             */
            vuln_moderate: number;
            /**
             * Vuln Low
             * @default 0
             */
            vuln_low: number;
            /**
             * Secret Count
             * @default 0
             */
            secret_count: number;
            /** Health Score */
            health_score?: number | null;
            /** Test Count */
            test_count?: number | null;
            /** Test File Count */
            test_file_count?: number | null;
            /** Test To Code Ratio */
            test_to_code_ratio?: number | null;
            /** Assertion Density */
            assertion_density?: number | null;
            /** Test Frameworks */
            test_frameworks?: string | null;
            /** Test Coverage Pct */
            test_coverage_pct?: number | null;
            /** Lint Issue Count */
            lint_issue_count?: number | null;
            /** Sast Issue Count */
            sast_issue_count?: number | null;
            /** Sast High */
            sast_high?: number | null;
            /** Sast Medium */
            sast_medium?: number | null;
            /** Sast Low */
            sast_low?: number | null;
            /** Dead Code Count */
            dead_code_count?: number | null;
            /** Bus Factor */
            bus_factor?: number | null;
            /** Top Author Share */
            top_author_share?: number | null;
            /** Active Contributor Count */
            active_contributor_count?: number | null;
            /** Commits Last 90D */
            commits_last_90d?: number | null;
            /** Days Since Last Commit */
            days_since_last_commit?: number | null;
            /** Maintenance Status */
            maintenance_status?: string | null;
            ratings?: components["schemas"]["Ratings"];
        };
        /** FactsResult */
        FactsResult: {
            /** First Commit At */
            first_commit_at: string | null;
            /** Last Commit At */
            last_commit_at: string | null;
            /** Age Days */
            age_days: number | null;
            /** Commit Count */
            commit_count: number;
            /** Contributor Count */
            contributor_count: number;
            /** Loc Total */
            loc_total: number;
            /** Primary Language */
            primary_language: string | null;
            /** License Spdx */
            license_spdx: string | null;
            /** License Name */
            license_name: string | null;
            /** Has Tests */
            has_tests: boolean;
            /** Dependency Count */
            dependency_count: number;
        };
        /**
         * GitProvider
         * @enum {string}
         */
        GitProvider: "github" | "gitlab" | "bitbucket" | "generic";
        /**
         * GraphResult
         * @description State of a repository's codebase graph (emerge) artifact.
         *
         *     Not part of the analysis snapshot — the graph is a standalone visualization artifact served
         *     under a static mount. `url` points at the generated interactive HTML app (iframe target) and is
         *     None until the graph has been generated.
         */
        GraphResult: {
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Generated */
            generated: boolean;
            /** Url */
            url?: string | null;
            /** Generated At */
            generated_at?: string | null;
            /** Scanned Files */
            scanned_files?: number | null;
            /** Node Count */
            node_count?: number | null;
            /**
             * Tool Available
             * @default false
             */
            tool_available: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthCheck */
        HealthCheck: {
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Reason */
            reason: string;
        };
        /**
         * Hotspot
         * @description A risk zone: changes often (churn) AND is large (size).
         */
        Hotspot: {
            /** Path */
            path: string;
            /** Churn */
            churn: number;
            /** Size */
            size: number;
            /** Score */
            score: number;
        };
        /**
         * IngestRepositoryRequest
         * @description Create input: a git URL to clone + analyze, optionally via a stored connection.
         */
        IngestRepositoryRequest: {
            /** Url */
            url: string;
            /** Connection Id */
            connection_id?: string | null;
        };
        /** LanguageStat */
        LanguageStat: {
            /** Language */
            language: string;
            /** Loc */
            loc: number;
            /** Files */
            files: number;
            /** Pct */
            pct: number;
        };
        /** MemberDetailResult */
        MemberDetailResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Anonymized */
            anonymized: boolean;
            /** Commits */
            commits: number;
            /** Lines Added */
            lines_added: number;
            /** Lines Removed */
            lines_removed: number;
            /** Files Touched */
            files_touched: number;
            /** First Active At */
            first_active_at: string | null;
            /** Last Active At */
            last_active_at: string | null;
            /** Status */
            status: string;
            /** Repositories */
            repositories: components["schemas"]["MemberRepositoryBreakdownResult"][];
        };
        /** MemberExclusionResult */
        MemberExclusionResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Pattern */
            pattern: string;
            /** Reason */
            reason: string | null;
            /** Is Bot */
            is_bot: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MemberRepositoryBreakdownResult */
        MemberRepositoryBreakdownResult: {
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Repository Name */
            repository_name: string;
            /** Commits */
            commits: number;
            /** Lines Added */
            lines_added: number;
            /** Lines Removed */
            lines_removed: number;
            /** Files Touched */
            files_touched: number;
        };
        /**
         * MemberSummaryResult
         * @description One aggregated identity across all repos (name/email pseudonymized when anonymized).
         */
        MemberSummaryResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Anonymized */
            anonymized: boolean;
            /** Commits */
            commits: number;
            /** Lines Added */
            lines_added: number;
            /** Lines Removed */
            lines_removed: number;
            /** Files Touched */
            files_touched: number;
            /** Repository Count */
            repository_count: number;
            /** First Active At */
            first_active_at: string | null;
            /** Last Active At */
            last_active_at: string | null;
            /** Status */
            status: string;
        };
        /** MembersOverviewResult */
        MembersOverviewResult: {
            health: components["schemas"]["PortfolioHealthResult"];
            /** Members */
            members: components["schemas"]["MemberSummaryResult"][];
        };
        /** Page[ConnectionResult] */
        Page_ConnectionResult_: {
            /** Items */
            items: components["schemas"]["ConnectionResult"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
        };
        /** Page[RepositoryResult] */
        Page_RepositoryResult_: {
            /** Items */
            items: components["schemas"]["RepositoryResult"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * PortfolioHealthResult
         * @description Fleet-wide collaboration health — the headline, framed around resilience not ranking.
         */
        PortfolioHealthResult: {
            /** Member Count */
            member_count: number;
            /** Active Member Count */
            active_member_count: number;
            /** Dormant Member Count */
            dormant_member_count: number;
            /** Repository Count */
            repository_count: number;
            /** Single Member Repositories */
            single_member_repositories: number;
            /** Knowledge Concentration */
            knowledge_concentration: number;
        };
        /**
         * Rating
         * @enum {string}
         */
        Rating: "A" | "B" | "C" | "D" | "E" | "NA";
        /**
         * Ratings
         * @description Derived A-E ratings (NA when the underlying tool didn't run).
         */
        Ratings: {
            /** @default NA */
            maintainability: components["schemas"]["Rating"];
            /** @default NA */
            security: components["schemas"]["Rating"];
            /** @default NA */
            health: components["schemas"]["Rating"];
        };
        /**
         * RepositoryResult
         * @description Result schema returned by the service/routes (never a SQLAlchemy entity).
         */
        RepositoryResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Provider */
            provider: string;
            /** Owner */
            owner: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Url */
            url: string;
            /** Connection Id */
            connection_id: string | null;
            /** Default Branch */
            default_branch: string;
            /** Status */
            status: string;
            /** Last Analyzed Commit */
            last_analyzed_commit: string | null;
            /** Last Analyzed At */
            last_analyzed_at: string | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TestConnectionRequest
         * @description Test unsaved credentials (from the form, before persisting).
         */
        TestConnectionRequest: {
            provider: components["schemas"]["GitProvider"];
            auth_method: components["schemas"]["AuthMethod"];
            /** Username */
            username?: string | null;
            /** Secret */
            secret?: string | null;
            /** Base Url */
            base_url?: string | null;
        };
        /**
         * TestConnectionResult
         * @description Result of a live credential check. `ok=False` is a normal outcome, not an error.
         */
        TestConnectionResult: {
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
            /** Account */
            account?: string | null;
        };
        /**
         * ToolLogResult
         * @description Raw findings log for one tool's latest run (lint/SAST/dead-code/secret locations).
         */
        ToolLogResult: {
            /** Tool */
            tool: string;
            /** Log */
            log?: string | null;
            /**
             * Line Count
             * @default 0
             */
            line_count: number;
        };
        /**
         * ToolRun
         * @description Which external tool ran for an analysis and whether it contributed data.
         *
         *     `log` holds the tool's raw findings text (lint violations, SAST hits, dead code, secret
         *     locations). It's excluded from API serialization to keep the analysis payload lean — fetch it
         *     on demand via the tool-log endpoint.
         */
        ToolRun: {
            /** Name */
            name: string;
            /** Available */
            available: boolean;
            /** Contributed */
            contributed: boolean;
        };
        /** ToolStatusResult */
        ToolStatusResult: {
            /** Name */
            name: string;
            /** Available */
            available: boolean;
            /** Version */
            version: string | null;
            /** Purpose */
            purpose: string;
            /** Install */
            install: string;
            /** Homepage */
            homepage: string;
            /** Id */
            id: string;
            /** Category */
            category: string;
            /** Kind */
            kind: string;
            /** Language */
            language: string;
            /** Synced At */
            synced_at?: string | null;
        };
        /**
         * UpdateConnection
         * @description Edit input. A blank/omitted `secret` keeps the existing one.
         */
        UpdateConnection: {
            /** Name */
            name: string;
            /** Username */
            username?: string | null;
            /** Secret */
            secret?: string | null;
            /** Base Url */
            base_url?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Vulnerability */
        Vulnerability: {
            /** Package */
            package: string;
            /** Ecosystem */
            ecosystem: string;
            /** Version */
            version?: string | null;
            /** Vuln Id */
            vuln_id: string;
            /** Severity */
            severity: string;
            /** Fixed Version */
            fixed_version?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_repositories_api_v1_repositories_get: {
        parameters: {
            query?: {
                /** @description 1-based page number */
                page?: number;
                /** @description Items per page */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RepositoryResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_repository_api_v1_repositories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRepositoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repository_api_v1_repositories__repository_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_repository_api_v1_repositories__repository_id__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_analysis_api_v1_repositories__repository_id__analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repositories_using_dependency_api_v1_dependencies__name__repositories_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DependencyUsageResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_tool_on_demand_api_v1_repositories__repository_id__tools__tool__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
                tool: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tool_log_api_v1_repositories__repository_id__tools__tool__log_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
                tool: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolLogResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    linked_integrations_api_v1_repositories__repository_id__integrations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_integration_api_v1_repositories__repository_id__integrations__tool_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
                tool_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlink_integration_api_v1_repositories__repository_id__integrations__tool_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
                tool_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    codebase_graph_api_v1_repositories__repository_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_codebase_graph_api_v1_repositories__repository_id__graph_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    code_age_api_v1_repositories__repository_id__code_age_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeAgeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_code_age_api_v1_repositories__repository_id__code_age_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeAgeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coupling_api_v1_repositories__repository_id__coupling_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CouplingResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_coupling_api_v1_repositories__repository_id__coupling_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CouplingResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    code_map_api_v1_repositories__repository_id__code_map_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeMapResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_code_map_api_v1_repositories__repository_id__code_map_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeMapResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_connections_api_v1_connections_get: {
        parameters: {
            query?: {
                /** @description 1-based page number */
                page?: number;
                /** @description Items per page */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ConnectionResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_connection_api_v1_connections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConnection"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_connection_api_v1_connections_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestConnectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestConnectionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_connection_api_v1_connections__connection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_connection_api_v1_connections__connection_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_connection_api_v1_connections__connection_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConnection"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_existing_connection_api_v1_connections__connection_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestConnectionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tools_api_v1_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolStatusResult"][];
                };
            };
        };
    };
    sync_tools_api_v1_tools_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolStatusResult"][];
                };
            };
        };
    };
    members_overview_api_v1_members_get: {
        parameters: {
            query?: {
                anonymize?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembersOverviewResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exclusions_api_v1_members_exclusions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberExclusionResult"][];
                };
            };
        };
    };
    add_exclusion_api_v1_members_exclusions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemberExclusion"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberExclusionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_exclusion_api_v1_members_exclusions__exclusion_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exclusion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    member_detail_api_v1_members__identity_id__get: {
        parameters: {
            query?: {
                anonymize?: boolean;
            };
            header?: never;
            path: {
                identity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberDetailResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
