/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Repositories */
        get: operations["list_repositories_api_v1_repositories_get"];
        put?: never;
        /**
         * Ingest Repository
         * @description Clone and analyze a repository from a git URL (blocking).
         */
        post: operations["ingest_repository_api_v1_repositories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Repository */
        get: operations["get_repository_api_v1_repositories__repository_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Repository
         * @description Pull the latest from the remote and re-run the full analysis.
         */
        post: operations["refresh_repository_api_v1_repositories__repository_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Analysis */
        get: operations["latest_analysis_api_v1_repositories__repository_id__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dependencies/{name}/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Repositories Using Dependency */
        get: operations["repositories_using_dependency_api_v1_dependencies__name__repositories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * External Tools
         * @description Availability + versions of the external analysis tools (drives docs + setup).
         */
        get: operations["external_tools_api_v1_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/tools/{tool}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Tool On Demand
         * @description Run a single external tool against the current clone and merge it into the analysis.
         */
        post: operations["run_tool_on_demand_api_v1_repositories__repository_id__tools__tool__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Codebase Graph
         * @description Whether a codebase graph exists for this repository and the URL to view it.
         */
        get: operations["codebase_graph_api_v1_repositories__repository_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/graph/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Codebase Graph
         * @description (Re)generate the interactive codebase graph (emerge) for the current clone.
         */
        post: operations["generate_codebase_graph_api_v1_repositories__repository_id__graph_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/code-age": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Code Age
         * @description Code age / survival over time (git-of-theseus): whether generated + the SVG URL.
         */
        get: operations["code_age_api_v1_repositories__repository_id__code_age_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/code-age/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Code Age
         * @description (Re)generate the code-age stacked-area chart (git-of-theseus) for the current clone.
         */
        post: operations["generate_code_age_api_v1_repositories__repository_id__code_age_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/coupling": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Coupling
         * @description Temporal (change) coupling (code-maat): ranked pairs of files that change together.
         */
        get: operations["coupling_api_v1_repositories__repository_id__coupling_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/coupling/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Coupling
         * @description (Re)compute temporal coupling (code-maat) from the current clone's git history.
         */
        post: operations["generate_coupling_api_v1_repositories__repository_id__coupling_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/code-map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Code Map
         * @description Code-city map (CodeCharta): whether generated + the viewer URL to iframe.
         */
        get: operations["code_map_api_v1_repositories__repository_id__code_map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/code-map/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Code Map
         * @description (Re)generate the CodeCharta code-city map for the current clone.
         */
        post: operations["generate_code_map_api_v1_repositories__repository_id__code_map_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResult */
        AnalysisResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Commit Sha */
            commit_sha: string;
            /**
             * Analyzed At
             * Format: date-time
             */
            analyzed_at: string;
            facts: components["schemas"]["FactsResult"];
            /** Contributors */
            contributors: components["schemas"]["Contributor"][];
            /** Commit Activity */
            commit_activity: components["schemas"]["DailyCommitCount"][];
            /** Languages */
            languages: components["schemas"]["LanguageStat"][];
            /** Dependencies */
            dependencies: components["schemas"]["Dependency"][];
            /** Cicd */
            cicd: components["schemas"]["CiCdConfig"][];
            /** Hotspots */
            hotspots: components["schemas"]["Hotspot"][];
            enrichment: components["schemas"]["Enrichment"];
            /** Vulnerabilities */
            vulnerabilities: components["schemas"]["Vulnerability"][];
            /** Health Checks */
            health_checks: components["schemas"]["HealthCheck"][];
            /** Tool Runs */
            tool_runs: components["schemas"]["ToolRun"][];
        };
        /** CiCdConfig */
        CiCdConfig: {
            system: components["schemas"]["CiCdSystem"];
            /** Config Files */
            config_files: string[];
        };
        /**
         * CiCdSystem
         * @enum {string}
         */
        CiCdSystem: "github_actions" | "gitlab_ci" | "circleci" | "jenkins" | "travis" | "azure_pipelines" | "drone" | "other";
        /** CodeAgeCohort */
        CodeAgeCohort: {
            /** Label */
            label: string;
            /** Lines */
            lines: number;
        };
        /**
         * CodeAgeResult
         * @description State of a repository's code-age artifact (git-of-theseus stacked-area SVG).
         *
         *     `url` points at the generated SVG (rendered as an image); `cohorts` is the surviving-lines
         *     breakdown per year as of the latest commit.
         */
        CodeAgeResult: {
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Generated */
            generated: boolean;
            /** Url */
            url?: string | null;
            /** Generated At */
            generated_at?: string | null;
            /**
             * Cohorts
             * @default []
             */
            cohorts: components["schemas"]["CodeAgeCohort"][];
            /**
             * Tool Available
             * @default false
             */
            tool_available: boolean;
        };
        /**
         * CodeMapResult
         * @description State of a repository's code-city map (CodeCharta).
         *
         *     `url` points at the CodeCharta browser viewer with the generated map loaded (iframe target).
         *     `viewer_available` is separate from `tool_available`: the analyzer (ccsh) and the viewer
         *     (codecharta-visualization) are installed independently.
         */
        CodeMapResult: {
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Generated */
            generated: boolean;
            /** Url */
            url?: string | null;
            /** Generated At */
            generated_at?: string | null;
            /** File Count */
            file_count?: number | null;
            /**
             * Tool Available
             * @default false
             */
            tool_available: boolean;
            /**
             * Viewer Available
             * @default false
             */
            viewer_available: boolean;
        };
        /** Contributor */
        Contributor: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Commits */
            commits: number;
            /** First Commit At */
            first_commit_at?: string | null;
            /** Last Commit At */
            last_commit_at?: string | null;
        };
        /** CouplingPair */
        CouplingPair: {
            /** Entity */
            entity: string;
            /** Coupled */
            coupled: string;
            /** Degree */
            degree: number;
            /** Average Revs */
            average_revs: number;
        };
        /**
         * CouplingResult
         * @description State of a repository's temporal-coupling analysis (code-maat).
         *
         *     Data, not an artifact: `pairs` are files that historically change together, ranked by coupling
         *     degree. Computed on demand and cached to disk so `generated_at` reflects the last run.
         */
        CouplingResult: {
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Generated */
            generated: boolean;
            /** Generated At */
            generated_at?: string | null;
            /**
             * Pairs
             * @default []
             */
            pairs: components["schemas"]["CouplingPair"][];
            /**
             * Tool Available
             * @default false
             */
            tool_available: boolean;
        };
        /** DailyCommitCount */
        DailyCommitCount: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Count */
            count: number;
        };
        /** Dependency */
        Dependency: {
            ecosystem: components["schemas"]["Ecosystem"];
            /** Name */
            name: string;
            /** Version */
            version?: string | null;
            /** Manifest File */
            manifest_file: string;
            /**
             * Is Dev
             * @default false
             */
            is_dev: boolean;
        };
        /** DependencyUsageResult */
        DependencyUsageResult: {
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Versions */
            versions: string[];
        };
        /**
         * Ecosystem
         * @enum {string}
         */
        Ecosystem: "pip" | "npm" | "cargo" | "go" | "maven" | "gem" | "composer" | "generic";
        /**
         * Enrichment
         * @description Scalar enrichment bundle embedded on an Analysis (all tool-sourced, best-effort).
         */
        Enrichment: {
            /** Code Lines */
            code_lines?: number | null;
            /** Complexity Total */
            complexity_total?: number | null;
            /** Cocomo Cost Usd */
            cocomo_cost_usd?: number | null;
            /** Schedule Months */
            schedule_months?: number | null;
            /** Ccn Average */
            ccn_average?: number | null;
            /** Ccn Max */
            ccn_max?: number | null;
            /** Function Count */
            function_count?: number | null;
            /** High Complexity Count */
            high_complexity_count?: number | null;
            /** Maintainability Index */
            maintainability_index?: number | null;
            /** Sbom Package Count */
            sbom_package_count?: number | null;
            /**
             * Vulnerability Count
             * @default 0
             */
            vulnerability_count: number;
            /**
             * Vuln Critical
             * @default 0
             */
            vuln_critical: number;
            /**
             * Vuln High
             * @default 0
             */
            vuln_high: number;
            /**
             * Vuln Moderate
             * @default 0
             */
            vuln_moderate: number;
            /**
             * Vuln Low
             * @default 0
             */
            vuln_low: number;
            /**
             * Secret Count
             * @default 0
             */
            secret_count: number;
            /** Health Score */
            health_score?: number | null;
            ratings?: components["schemas"]["Ratings"];
        };
        /** FactsResult */
        FactsResult: {
            /** First Commit At */
            first_commit_at: string | null;
            /** Last Commit At */
            last_commit_at: string | null;
            /** Age Days */
            age_days: number | null;
            /** Commit Count */
            commit_count: number;
            /** Contributor Count */
            contributor_count: number;
            /** Loc Total */
            loc_total: number;
            /** Primary Language */
            primary_language: string | null;
            /** License Spdx */
            license_spdx: string | null;
            /** License Name */
            license_name: string | null;
            /** Has Tests */
            has_tests: boolean;
            /** Dependency Count */
            dependency_count: number;
        };
        /**
         * GraphResult
         * @description State of a repository's codebase graph (emerge) artifact.
         *
         *     Not part of the analysis snapshot — the graph is a standalone visualization artifact served
         *     under a static mount. `url` points at the generated interactive HTML app (iframe target) and is
         *     None until the graph has been generated.
         */
        GraphResult: {
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Generated */
            generated: boolean;
            /** Url */
            url?: string | null;
            /** Generated At */
            generated_at?: string | null;
            /** Scanned Files */
            scanned_files?: number | null;
            /** Node Count */
            node_count?: number | null;
            /**
             * Tool Available
             * @default false
             */
            tool_available: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthCheck */
        HealthCheck: {
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Reason */
            reason: string;
        };
        /**
         * Hotspot
         * @description A risk zone: changes often (churn) AND is large (size).
         */
        Hotspot: {
            /** Path */
            path: string;
            /** Churn */
            churn: number;
            /** Size */
            size: number;
            /** Score */
            score: number;
        };
        /**
         * IngestRepositoryRequest
         * @description Create input: a git URL to clone + analyze.
         */
        IngestRepositoryRequest: {
            /** Url */
            url: string;
        };
        /** LanguageStat */
        LanguageStat: {
            /** Language */
            language: string;
            /** Loc */
            loc: number;
            /** Files */
            files: number;
            /** Pct */
            pct: number;
        };
        /** Page[RepositoryResult] */
        Page_RepositoryResult_: {
            /** Items */
            items: components["schemas"]["RepositoryResult"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * Rating
         * @enum {string}
         */
        Rating: "A" | "B" | "C" | "D" | "E" | "NA";
        /**
         * Ratings
         * @description Derived A-E ratings (NA when the underlying tool didn't run).
         */
        Ratings: {
            /** @default NA */
            maintainability: components["schemas"]["Rating"];
            /** @default NA */
            security: components["schemas"]["Rating"];
            /** @default NA */
            health: components["schemas"]["Rating"];
        };
        /**
         * RepositoryResult
         * @description Result schema returned by the service/routes (never a SQLAlchemy entity).
         */
        RepositoryResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Provider */
            provider: string;
            /** Owner */
            owner: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Url */
            url: string;
            /** Default Branch */
            default_branch: string;
            /** Status */
            status: string;
            /** Last Analyzed Commit */
            last_analyzed_commit: string | null;
            /** Last Analyzed At */
            last_analyzed_at: string | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ToolRun
         * @description Which external tool ran for an analysis and whether it contributed data.
         */
        ToolRun: {
            /** Name */
            name: string;
            /** Available */
            available: boolean;
            /** Contributed */
            contributed: boolean;
        };
        /** ToolStatusResult */
        ToolStatusResult: {
            /** Name */
            name: string;
            /** Available */
            available: boolean;
            /** Version */
            version: string | null;
            /** Purpose */
            purpose: string;
            /** Install */
            install: string;
            /** Homepage */
            homepage: string;
            /** Id */
            id: string;
            /** Category */
            category: string;
            /** Kind */
            kind: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Vulnerability */
        Vulnerability: {
            /** Package */
            package: string;
            /** Ecosystem */
            ecosystem: string;
            /** Version */
            version?: string | null;
            /** Vuln Id */
            vuln_id: string;
            /** Severity */
            severity: string;
            /** Fixed Version */
            fixed_version?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_repositories_api_v1_repositories_get: {
        parameters: {
            query?: {
                /** @description 1-based page number */
                page?: number;
                /** @description Items per page */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RepositoryResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_repository_api_v1_repositories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRepositoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repository_api_v1_repositories__repository_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_repository_api_v1_repositories__repository_id__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_analysis_api_v1_repositories__repository_id__analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repositories_using_dependency_api_v1_dependencies__name__repositories_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DependencyUsageResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    external_tools_api_v1_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolStatusResult"][];
                };
            };
        };
    };
    run_tool_on_demand_api_v1_repositories__repository_id__tools__tool__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
                tool: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    codebase_graph_api_v1_repositories__repository_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_codebase_graph_api_v1_repositories__repository_id__graph_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    code_age_api_v1_repositories__repository_id__code_age_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeAgeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_code_age_api_v1_repositories__repository_id__code_age_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeAgeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coupling_api_v1_repositories__repository_id__coupling_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CouplingResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_coupling_api_v1_repositories__repository_id__coupling_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CouplingResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    code_map_api_v1_repositories__repository_id__code_map_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeMapResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_code_map_api_v1_repositories__repository_id__code_map_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeMapResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
