"""The git + provider mechanics behind roadmap item executions.

Everything credentialed happens here, in the backend — the agent only ever sees the worktree.
The credential enters as a `ProviderCredential`, is used transiently for `git push` and the PR
API call, and is scrubbed out of any error text before it can be persisted.
"""

from __future__ import annotations

import contextlib
import logging
import uuid
from pathlib import Path

from sqlalchemy.orm import Session

from hobits.core.settings import get_settings
from hobits.domain.connections.domain import PullRequestRef
from hobits.domain.connections.services import ConnectionService
from hobits.domain.repository.domain import GitProvider
from hobits.domain.repository.models import RepositoryRow
from hobits.domain.roadmap.models import RoadmapExecutionRow, RoadmapItemRow
from hobits.integrations.git_providers.registry import get_connector
from hobits.integrations.git_worktree import (
    add_worktree,
    commit_all,
    push_branch,
    remove_worktree,
    scrub_secrets,
)

logger = logging.getLogger(__name__)

_PR_BODY_FOOTER = "\n\n---\n🤖 Generated by [hobits](https://github.com/hobits) roadmap execution."


class ExecutionError(Exception):
    """An execution step failed with a message safe to persist (secrets already scrubbed)."""


def worktree_path_for(repository_id: uuid.UUID, branch: str) -> Path:
    """`<worktree_root>/<repo_id>/<branch-leaf>` — one disposable checkout per execution."""
    leaf = branch.rsplit("/", 1)[-1]
    return (get_settings().worktree_root / str(repository_id) / leaf).resolve()


def create_execution_worktree(repo: RepositoryRow, branch: str) -> tuple[Path, str]:
    """The isolated checkout the agent will write in. Returns (path, base sha)."""
    if not repo.clone_path:
        raise ExecutionError("The repository has no local clone yet.")
    path = worktree_path_for(repo.id, branch)
    try:
        base_sha = add_worktree(Path(repo.clone_path), path, branch, repo.default_branch)
    except Exception as exc:
        raise ExecutionError(f"Could not create the execution worktree: {exc}") from exc
    return path, base_sha


def finalize_execution(
    session: Session,
    execution: RoadmapExecutionRow,
    item: RoadmapItemRow,
    repo: RepositoryRow,
) -> PullRequestRef:
    """Commit the worktree diff, push the branch with a transient credentialed URL, open the PR.

    Raises ExecutionError with a scrubbed message on any failure.
    """
    if not execution.worktree_path or not repo.clone_path:
        raise ExecutionError("The execution worktree is gone.")
    worktree = Path(execution.worktree_path)
    if not worktree.is_dir():
        raise ExecutionError("The execution worktree is gone.")

    commit_sha = commit_all(worktree, f"Roadmap: {item.title}")
    if commit_sha is None:
        raise ExecutionError("The agent finished without changing any files.")
    execution.commit_sha = commit_sha

    if repo.connection_id is None:
        raise ExecutionError("The repository has no connection to push with.")
    credential = ConnectionService(session).resolve_credential(repo.connection_id)
    if credential is None:
        raise ExecutionError("The repository's connection no longer exists.")

    connector = get_connector(GitProvider(repo.provider))
    authenticated = connector.authenticated_url(repo.url, credential)
    try:
        push_branch(worktree, authenticated, execution.branch)
        pr = connector.create_pull_request(
            credential,
            repo.owner,
            repo.name,
            head=execution.branch,
            base=repo.default_branch,
            title=f"Roadmap: {item.title}",
            body=_pr_body(execution, item),
        )
    except ExecutionError:
        raise
    except Exception as exc:
        raise ExecutionError(scrub_secrets(str(exc), [credential.secret])) from exc
    return pr


def cleanup_execution_worktree(execution: RoadmapExecutionRow, repo: RepositoryRow | None) -> None:
    """Always-run teardown: the branch is on the remote (or worthless) — the checkout never is."""
    if not execution.worktree_path:
        return
    clone_path = Path(repo.clone_path) if repo is not None and repo.clone_path else None
    if clone_path is not None:
        remove_worktree(clone_path, Path(execution.worktree_path), execution.branch)
    execution.worktree_path = None


def cleanup_orphan_worktrees(session: Session) -> int:
    """Sweep `<worktree_root>` for directories no pending execution owns (crash leftovers)."""
    from sqlalchemy import select

    root = get_settings().worktree_root
    if not root.is_dir():
        return 0
    live = {
        Path(path).resolve()
        for path in session.scalars(
            select(RoadmapExecutionRow.worktree_path).where(
                RoadmapExecutionRow.status == "pending",
                RoadmapExecutionRow.worktree_path.is_not(None),
            )
        )
    }
    removed = 0
    for repo_dir in root.iterdir():
        if not repo_dir.is_dir():
            continue
        repo = None
        with contextlib.suppress(ValueError):
            repo = session.get(RepositoryRow, uuid.UUID(repo_dir.name))
        for worktree in repo_dir.iterdir():
            if worktree.resolve() in live:
                continue
            clone = Path(repo.clone_path) if repo is not None and repo.clone_path else worktree
            remove_worktree(clone, worktree)
            removed += 1
        if not any(repo_dir.iterdir()):
            repo_dir.rmdir()
    if removed:
        logger.info("Removed %d orphaned roadmap worktrees.", removed)
    return removed


def _pr_body(execution: RoadmapExecutionRow, item: RoadmapItemRow) -> str:
    parts = []
    if execution.agent_summary:
        parts.append(execution.agent_summary.strip())
    if item.description:
        parts.append(f"### Roadmap item\n{item.description.strip()}")
    if item.rationale:
        parts.append(f"### Why\n{item.rationale.strip()}")
    return "\n\n".join(parts) + _PR_BODY_FOOTER
