"""principles

Revision ID: 08ed12202356
Revises: 1ba8d4772ca6
Create Date: 2026-07-15 23:51:56.672357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08ed12202356'
down_revision: Union[str, Sequence[str], None] = '1ba8d4772ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('principles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), server_default='warning', nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_principles_repository_id'), 'principles', ['repository_id'], unique=False)
    op.create_table('principle_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('principle_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('violations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['principle_id'], ['principles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_principle_checks_pair_created', 'principle_checks', ['principle_id', 'repository_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_principle_checks_principle_id'), 'principle_checks', ['principle_id'], unique=False)
    op.create_index(op.f('ix_principle_checks_repository_id'), 'principle_checks', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_principle_checks_repository_id'), table_name='principle_checks')
    op.drop_index(op.f('ix_principle_checks_principle_id'), table_name='principle_checks')
    op.drop_index('ix_principle_checks_pair_created', table_name='principle_checks')
    op.drop_table('principle_checks')
    op.drop_index(op.f('ix_principles_repository_id'), table_name='principles')
    op.drop_table('principles')
    # ### end Alembic commands ###
