"""initial substrate schema

Revision ID: 09c78fc372a0
Revises:
Create Date: 2026-07-06 23:47:20.647374

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09c78fc372a0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analyses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("commit_sha", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_commit_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_commit_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("commit_count", sa.Integer(), nullable=False),
        sa.Column("contributor_count", sa.Integer(), nullable=False),
        sa.Column("loc_total", sa.Integer(), nullable=False),
        sa.Column("primary_language", sa.String(length=64), nullable=True),
        sa.Column("license_spdx", sa.String(length=64), nullable=True),
        sa.Column("license_name", sa.String(length=255), nullable=True),
        sa.Column("license_source_file", sa.String(length=255), nullable=True),
        sa.Column("has_tests", sa.Boolean(), nullable=False),
        sa.Column("dependency_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "commit_sha", name="uq_analysis_repo_commit"),
    )
    op.create_index(op.f("ix_analyses_repository_id"), "analyses", ["repository_id"], unique=False)
    op.create_table(
        "repositories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("default_branch", sa.String(length=255), nullable=False),
        sa.Column("clone_path", sa.String(length=1024), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("last_analyzed_commit", sa.String(length=64), nullable=True),
        sa.Column("last_analyzed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "owner", "name", name="uq_repo_coordinates"),
    )
    op.create_table(
        "cicd_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("system", sa.String(length=32), nullable=False),
        sa.Column("config_files", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cicd_configs_analysis_id"), "cicd_configs", ["analysis_id"], unique=False
    )
    op.create_table(
        "code_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(384), nullable=True),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_code_chunks_analysis_id"), "code_chunks", ["analysis_id"], unique=False
    )
    op.create_table(
        "commit_activity",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_commit_activity_analysis_id"), "commit_activity", ["analysis_id"], unique=False
    )
    op.create_table(
        "contributors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("commits", sa.Integer(), nullable=False),
        sa.Column("first_commit_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_commit_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contributors_analysis_id"), "contributors", ["analysis_id"], unique=False
    )
    op.create_table(
        "dependencies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("ecosystem", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=True),
        sa.Column("manifest_file", sa.String(length=255), nullable=False),
        sa.Column("is_dev", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dependencies_analysis_id"), "dependencies", ["analysis_id"], unique=False
    )
    op.create_index(op.f("ix_dependencies_ecosystem"), "dependencies", ["ecosystem"], unique=False)
    op.create_index(op.f("ix_dependencies_name"), "dependencies", ["name"], unique=False)
    op.create_table(
        "hotspots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("churn", sa.Integer(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hotspots_analysis_id"), "hotspots", ["analysis_id"], unique=False)
    op.create_table(
        "language_stats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("language", sa.String(length=64), nullable=False),
        sa.Column("loc", sa.Integer(), nullable=False),
        sa.Column("files", sa.Integer(), nullable=False),
        sa.Column("pct", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_language_stats_analysis_id"), "language_stats", ["analysis_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_language_stats_analysis_id"), table_name="language_stats")
    op.drop_table("language_stats")
    op.drop_index(op.f("ix_hotspots_analysis_id"), table_name="hotspots")
    op.drop_table("hotspots")
    op.drop_index(op.f("ix_dependencies_name"), table_name="dependencies")
    op.drop_index(op.f("ix_dependencies_ecosystem"), table_name="dependencies")
    op.drop_index(op.f("ix_dependencies_analysis_id"), table_name="dependencies")
    op.drop_table("dependencies")
    op.drop_index(op.f("ix_contributors_analysis_id"), table_name="contributors")
    op.drop_table("contributors")
    op.drop_index(op.f("ix_commit_activity_analysis_id"), table_name="commit_activity")
    op.drop_table("commit_activity")
    op.drop_index(op.f("ix_code_chunks_analysis_id"), table_name="code_chunks")
    op.drop_table("code_chunks")
    op.drop_index(op.f("ix_cicd_configs_analysis_id"), table_name="cicd_configs")
    op.drop_table("cicd_configs")
    op.drop_table("repositories")
    op.drop_index(op.f("ix_analyses_repository_id"), table_name="analyses")
    op.drop_table("analyses")
    # ### end Alembic commands ###
