"""ai readiness

Revision ID: 1605927ddf9e
Revises: 99b2bd4fa821
Create Date: 2026-07-26 18:22:27.133914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1605927ddf9e'
down_revision: Union[str, Sequence[str], None] = '99b2bd4fa821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readiness_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('branch', sa.String(length=160), nullable=False),
    sa.Column('worktree_path', sa.String(length=500), nullable=True),
    sa.Column('base_sha', sa.String(length=64), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('agent_summary', sa.Text(), nullable=False),
    sa.Column('suggestion_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'succeeded', 'failed')", name='ck_readiness_executions_status'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readiness_executions_repository_id'), 'readiness_executions', ['repository_id'], unique=False)
    op.create_table('readiness_suggestions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('assistant', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('add', 'edit')", name='ck_readiness_suggestions_action'),
    sa.CheckConstraint("status IN ('proposed', 'applied')", name='ck_readiness_suggestions_status'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readiness_suggestions_repository_id'), 'readiness_suggestions', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readiness_suggestions_repository_id'), table_name='readiness_suggestions')
    op.drop_table('readiness_suggestions')
    op.drop_index(op.f('ix_readiness_executions_repository_id'), table_name='readiness_executions')
    op.drop_table('readiness_executions')
    # ### end Alembic commands ###
