"""repository current_branch

Revision ID: 1ba8d4772ca6
Revises: 884624f823a4
Create Date: 2026-07-15 21:57:27.279791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba8d4772ca6'
down_revision: Union[str, Sequence[str], None] = '884624f823a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('current_branch', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'current_branch')
    # ### end Alembic commands ###
