"""principle tech

Revision ID: 3c169c8027e0
Revises: 8e889d287b9e
Create Date: 2026-07-26 21:49:16.966679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c169c8027e0'
down_revision: Union[str, Sequence[str], None] = '8e889d287b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('principles', sa.Column('tech', sa.String(length=20), server_default='general', nullable=False))
    op.create_check_constraint('ck_principles_tech', 'principles', "tech IN ('general', 'python', 'sql')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_principles_tech', 'principles', type_='check')
    op.drop_column('principles', 'tech')
    # ### end Alembic commands ###
