"""roadmaps

Revision ID: 4b354a708379
Revises: d1eb80ad5e2c
Create Date: 2026-07-16 10:51:34.285860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b354a708379'
down_revision: Union[str, Sequence[str], None] = 'd1eb80ad5e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmaps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['roadmap_versions.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('roadmap_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('goal_snapshot', sa.Text(), nullable=True),
    sa.Column('repository_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assessments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roadmap_id', 'number', name='uq_roadmap_versions_roadmap_number')
    )
    op.create_index(op.f('ix_roadmap_versions_roadmap_id'), 'roadmap_versions', ['roadmap_id'], unique=False)
    op.create_table('roadmap_milestones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['roadmap_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_milestones_version_id'), 'roadmap_milestones', ['version_id'], unique=False)
    op.create_table('roadmap_repositories',
    sa.Column('roadmap_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('roadmap_id', 'repository_id')
    )
    op.create_table('roadmap_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('milestone_id', sa.Uuid(), nullable=True),
    sa.Column('repository_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('urgent', sa.Boolean(), nullable=False),
    sa.Column('important', sa.Boolean(), nullable=False),
    sa.Column('effort', sa.String(length=4), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='proposed', nullable=False),
    sa.Column('carried_from_item_id', sa.Uuid(), nullable=True),
    sa.Column('issue_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['roadmap_milestones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['roadmap_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_items_milestone_id'), 'roadmap_items', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_roadmap_items_repository_id'), 'roadmap_items', ['repository_id'], unique=False)
    op.create_index(op.f('ix_roadmap_items_version_id'), 'roadmap_items', ['version_id'], unique=False)
    op.create_index('ix_roadmap_items_version_status', 'roadmap_items', ['version_id', 'status'], unique=False)
    op.create_table('roadmap_item_dependencies',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('depends_on_item_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.String(length=8), nullable=False),
    sa.CheckConstraint('item_id != depends_on_item_id', name='ck_roadmap_dep_not_self'),
    sa.ForeignKeyConstraint(['depends_on_item_id'], ['roadmap_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['roadmap_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'depends_on_item_id')
    )
    op.create_table('roadmap_item_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('roadmap_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('from_value', sa.String(length=32), nullable=True),
    sa.Column('to_value', sa.String(length=32), nullable=True),
    sa.Column('actor', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['roadmap_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_item_events_item_id'), 'roadmap_item_events', ['item_id'], unique=False)
    op.create_index('ix_roadmap_item_events_roadmap_created', 'roadmap_item_events', ['roadmap_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_roadmap_item_events_roadmap_id'), 'roadmap_item_events', ['roadmap_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_item_events_roadmap_id'), table_name='roadmap_item_events')
    op.drop_index('ix_roadmap_item_events_roadmap_created', table_name='roadmap_item_events')
    op.drop_index(op.f('ix_roadmap_item_events_item_id'), table_name='roadmap_item_events')
    op.drop_table('roadmap_item_events')
    op.drop_table('roadmap_item_dependencies')
    op.drop_index('ix_roadmap_items_version_status', table_name='roadmap_items')
    op.drop_index(op.f('ix_roadmap_items_version_id'), table_name='roadmap_items')
    op.drop_index(op.f('ix_roadmap_items_repository_id'), table_name='roadmap_items')
    op.drop_index(op.f('ix_roadmap_items_milestone_id'), table_name='roadmap_items')
    op.drop_table('roadmap_items')
    op.drop_table('roadmap_repositories')
    op.drop_index(op.f('ix_roadmap_milestones_version_id'), table_name='roadmap_milestones')
    op.drop_table('roadmap_milestones')
    op.drop_index(op.f('ix_roadmap_versions_roadmap_id'), table_name='roadmap_versions')
    op.drop_table('roadmap_versions')
    op.drop_table('roadmaps')
    # ### end Alembic commands ###
