"""add testing quality ownership metrics

Revision ID: 756cb15bd2dd
Revises: b1c2d3e4f5a6
Create Date: 2026-07-08 14:52:06.838755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756cb15bd2dd'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('test_count', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('test_file_count', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('test_to_code_ratio', sa.Float(), nullable=True))
    op.add_column('analyses', sa.Column('assertion_density', sa.Float(), nullable=True))
    op.add_column('analyses', sa.Column('test_frameworks', sa.String(length=255), nullable=True))
    op.add_column('analyses', sa.Column('test_coverage_pct', sa.Float(), nullable=True))
    op.add_column('analyses', sa.Column('lint_issue_count', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('sast_issue_count', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('sast_high', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('sast_medium', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('sast_low', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('dead_code_count', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('bus_factor', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('top_author_share', sa.Float(), nullable=True))
    op.add_column('analyses', sa.Column('active_contributor_count', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('commits_last_90d', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('days_since_last_commit', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('maintenance_status', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'maintenance_status')
    op.drop_column('analyses', 'days_since_last_commit')
    op.drop_column('analyses', 'commits_last_90d')
    op.drop_column('analyses', 'active_contributor_count')
    op.drop_column('analyses', 'top_author_share')
    op.drop_column('analyses', 'bus_factor')
    op.drop_column('analyses', 'dead_code_count')
    op.drop_column('analyses', 'sast_low')
    op.drop_column('analyses', 'sast_medium')
    op.drop_column('analyses', 'sast_high')
    op.drop_column('analyses', 'sast_issue_count')
    op.drop_column('analyses', 'lint_issue_count')
    op.drop_column('analyses', 'test_coverage_pct')
    op.drop_column('analyses', 'test_frameworks')
    op.drop_column('analyses', 'assertion_density')
    op.drop_column('analyses', 'test_to_code_ratio')
    op.drop_column('analyses', 'test_file_count')
    op.drop_column('analyses', 'test_count')
    # ### end Alembic commands ###
