"""remove archetypes

Revision ID: 7a56a9f3d7e2
Revises: 6e26b58f7c76
Create Date: 2026-07-26 20:06:53.968462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a56a9f3d7e2'
down_revision: Union[str, Sequence[str], None] = '6e26b58f7c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_archetypes_family'), table_name='project_archetypes')
    op.drop_table('project_archetypes')
    op.drop_column('architecture_blueprints', 'archetype_slugs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('architecture_blueprints', sa.Column('archetype_slugs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.create_table('project_archetypes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('family', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('summary', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('supports_greenfield', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('supports_brownfield', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_initiative', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('typical_category_slugs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('default_blueprint_slugs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('seed_tier', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('archived', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("family::text = ANY (ARRAY['acquisition-ingestion'::character varying, 'movement-migration'::character varying, 'transformation-modelling'::character varying, 'storage-platform'::character varying, 'streaming-realtime'::character varying, 'orchestration-dataops'::character varying, 'governance-security-compliance'::character varying, 'analytics-serving'::character varying, 'ml-ai-infrastructure'::character varying, 'discovery-strategy'::character varying]::text[])", name=op.f('ck_project_archetypes_family')),
    sa.CheckConstraint("source::text = ANY (ARRAY['seed'::character varying, 'user'::character varying]::text[])", name=op.f('ck_project_archetypes_source')),
    sa.CheckConstraint('seed_tier = ANY (ARRAY[1, 2, 3])', name=op.f('ck_project_archetypes_seed_tier')),
    sa.PrimaryKeyConstraint('id', name=op.f('project_archetypes_pkey')),
    sa.UniqueConstraint('slug', name=op.f('project_archetypes_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_project_archetypes_family'), 'project_archetypes', ['family'], unique=False)
    # ### end Alembic commands ###
