"""add tool_run log

Revision ID: 7c9a0e6a4f51
Revises: 756cb15bd2dd
Create Date: 2026-07-08 15:14:42.754489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9a0e6a4f51'
down_revision: Union[str, Sequence[str], None] = '756cb15bd2dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_runs', sa.Column('log', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool_runs', 'log')
    # ### end Alembic commands ###
