"""repository_tools link table

Revision ID: 7f6b7230f559
Revises: 89d0840f86c3
Create Date: 2026-07-08 17:11:19.579811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6b7230f559'
down_revision: Union[str, Sequence[str], None] = '89d0840f86c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_tools',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.String(length=64), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('repository_id', 'tool_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repository_tools')
    # ### end Alembic commands ###
