"""roadmap executions and config

Revision ID: 803ea6d2f00c
Revises: 4b354a708379
Create Date: 2026-07-16 11:23:33.482186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '803ea6d2f00c'
down_revision: Union[str, Sequence[str], None] = '4b354a708379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_timeout_seconds', sa.Float(), server_default='900', nullable=False),
    sa.Column('drift_cadence', sa.String(length=64), server_default='manual', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('worktree_path', sa.String(length=1024), nullable=True),
    sa.Column('base_sha', sa.String(length=64), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('pr_url', sa.String(length=1024), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_state', sa.String(length=16), nullable=True),
    sa.Column('agent_summary', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['roadmap_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_executions_item_id'), 'roadmap_executions', ['item_id'], unique=False)
    op.create_foreign_key('fk_roadmaps_current_version', 'roadmaps', 'roadmap_versions', ['current_version_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_roadmaps_current_version', 'roadmaps', type_='foreignkey')
    op.drop_index(op.f('ix_roadmap_executions_item_id'), table_name='roadmap_executions')
    op.drop_table('roadmap_executions')
    op.drop_table('roadmap_config')
    # ### end Alembic commands ###
