"""engine config + cancelled status

Revision ID: 884624f823a4
Revises: 2694a8ae0f19
Create Date: 2026-07-15 19:24:26.843804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '884624f823a4'
down_revision: Union[str, Sequence[str], None] = '2694a8ae0f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Float(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Hand-added: autogenerate can't diff partial-index predicates. The dispatcher sweep
    # must also pick up user-cancelled jobs, so the WHERE clause gains 'cancelled'.
    op.drop_index('ix_jobs_unapplied', table_name='jobs')
    op.create_index(
        'ix_jobs_unapplied',
        'jobs',
        ['finished_at'],
        unique=False,
        postgresql_where=sa.text(
            "status IN ('succeeded','failed','cancelled') AND NOT result_applied"
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_jobs_unapplied', table_name='jobs')
    op.create_index(
        'ix_jobs_unapplied',
        'jobs',
        ['finished_at'],
        unique=False,
        postgresql_where=sa.text("status IN ('succeeded','failed') AND NOT result_applied"),
    )
    op.drop_table('engine_config')
