"""principle slug and source

Revision ID: 8e889d287b9e
Revises: 7f7fc2b98bbb
Create Date: 2026-07-26 21:32:46.004035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e889d287b9e'
down_revision: Union[str, Sequence[str], None] = '7f7fc2b98bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('principles', sa.Column('slug', sa.String(length=160), nullable=True))
    op.add_column('principles', sa.Column('source', sa.String(length=10), server_default='user', nullable=False))
    op.create_unique_constraint(op.f('uq_principles_slug'), 'principles', ['slug'])
    op.create_check_constraint('ck_principles_source', 'principles', "source IN ('seed', 'user')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_principles_source', 'principles', type_='check')
    op.drop_constraint(op.f('uq_principles_slug'), 'principles', type_='unique')
    op.drop_column('principles', 'source')
    op.drop_column('principles', 'slug')
    # ### end Alembic commands ###
