"""phase 1.5 enrichment

Revision ID: 8f6596f52b90
Revises: 09c78fc372a0
Create Date: 2026-07-07 00:48:16.991634

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f6596f52b90"
down_revision: str | Sequence[str] | None = "09c78fc372a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "health_checks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_health_checks_analysis_id"), "health_checks", ["analysis_id"], unique=False
    )
    op.create_table(
        "tool_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column("contributed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tool_runs_analysis_id"), "tool_runs", ["analysis_id"], unique=False)
    op.create_table(
        "vulnerabilities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("package", sa.String(length=255), nullable=False),
        sa.Column("ecosystem", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=True),
        sa.Column("vuln_id", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("fixed_version", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vulnerabilities_analysis_id"), "vulnerabilities", ["analysis_id"], unique=False
    )
    op.create_index(
        op.f("ix_vulnerabilities_package"), "vulnerabilities", ["package"], unique=False
    )
    op.add_column("analyses", sa.Column("code_lines", sa.Integer(), nullable=True))
    op.add_column("analyses", sa.Column("complexity_total", sa.Integer(), nullable=True))
    op.add_column("analyses", sa.Column("cocomo_cost_usd", sa.Float(), nullable=True))
    op.add_column("analyses", sa.Column("schedule_months", sa.Float(), nullable=True))
    op.add_column("analyses", sa.Column("ccn_average", sa.Float(), nullable=True))
    op.add_column("analyses", sa.Column("ccn_max", sa.Integer(), nullable=True))
    op.add_column("analyses", sa.Column("function_count", sa.Integer(), nullable=True))
    op.add_column("analyses", sa.Column("high_complexity_count", sa.Integer(), nullable=True))
    op.add_column("analyses", sa.Column("maintainability_index", sa.Float(), nullable=True))
    op.add_column("analyses", sa.Column("sbom_package_count", sa.Integer(), nullable=True))
    op.add_column(
        "analyses",
        sa.Column("vulnerability_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "analyses", sa.Column("vuln_critical", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "analyses", sa.Column("vuln_high", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "analyses", sa.Column("vuln_moderate", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "analyses", sa.Column("vuln_low", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "analyses", sa.Column("secret_count", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column("analyses", sa.Column("health_score", sa.Float(), nullable=True))
    op.add_column(
        "analyses",
        sa.Column(
            "rating_maintainability", sa.String(length=2), nullable=False, server_default="NA"
        ),
    )
    op.add_column(
        "analyses",
        sa.Column("rating_security", sa.String(length=2), nullable=False, server_default="NA"),
    )
    op.add_column(
        "analyses",
        sa.Column("rating_health", sa.String(length=2), nullable=False, server_default="NA"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analyses", "rating_health")
    op.drop_column("analyses", "rating_security")
    op.drop_column("analyses", "rating_maintainability")
    op.drop_column("analyses", "health_score")
    op.drop_column("analyses", "secret_count")
    op.drop_column("analyses", "vuln_low")
    op.drop_column("analyses", "vuln_moderate")
    op.drop_column("analyses", "vuln_high")
    op.drop_column("analyses", "vuln_critical")
    op.drop_column("analyses", "vulnerability_count")
    op.drop_column("analyses", "sbom_package_count")
    op.drop_column("analyses", "maintainability_index")
    op.drop_column("analyses", "high_complexity_count")
    op.drop_column("analyses", "function_count")
    op.drop_column("analyses", "ccn_max")
    op.drop_column("analyses", "ccn_average")
    op.drop_column("analyses", "schedule_months")
    op.drop_column("analyses", "cocomo_cost_usd")
    op.drop_column("analyses", "complexity_total")
    op.drop_column("analyses", "code_lines")
    op.drop_index(op.f("ix_vulnerabilities_package"), table_name="vulnerabilities")
    op.drop_index(op.f("ix_vulnerabilities_analysis_id"), table_name="vulnerabilities")
    op.drop_table("vulnerabilities")
    op.drop_index(op.f("ix_tool_runs_analysis_id"), table_name="tool_runs")
    op.drop_table("tool_runs")
    op.drop_index(op.f("ix_health_checks_analysis_id"), table_name="health_checks")
    op.drop_table("health_checks")
    # ### end Alembic commands ###
