"""compliance checks + capacity calculations

Revision ID: 99b2bd4fa821
Revises: be3a8f12f954
Create Date: 2026-07-26 14:48:35.201350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99b2bd4fa821'
down_revision: Union[str, Sequence[str], None] = 'be3a8f12f954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capacity_calculations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('repository_slug', sa.String(length=320), nullable=False),
    sa.Column('regulation_slug', sa.String(length=160), nullable=False),
    sa.Column('regulation_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'done', 'failed')", name='ck_compliance_checks_status'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_checks_regulation_slug'), 'compliance_checks', ['regulation_slug'], unique=False)
    op.create_index(op.f('ix_compliance_checks_repository_id'), 'compliance_checks', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_checks_repository_id'), table_name='compliance_checks')
    op.drop_index(op.f('ix_compliance_checks_regulation_slug'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    op.drop_table('capacity_calculations')
    # ### end Alembic commands ###
