"""add contributor churn metrics and member exclusions

Revision ID: a257fed3a335
Revises: 7f6b7230f559
Create Date: 2026-07-08 17:27:17.050212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a257fed3a335'
down_revision: Union[str, Sequence[str], None] = '7f6b7230f559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_exclusions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pattern', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern')
    )
    # server_default backfills existing contributor rows (pre-churn analyses) with 0.
    op.add_column(
        'contributors',
        sa.Column('lines_added', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'contributors',
        sa.Column('lines_removed', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'contributors',
        sa.Column('files_touched', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributors', 'files_touched')
    op.drop_column('contributors', 'lines_removed')
    op.drop_column('contributors', 'lines_added')
    op.drop_table('member_exclusions')
    # ### end Alembic commands ###
