"""knowledge catalogs

Revision ID: be3a8f12f954
Revises: c4a1b2d3e4f5
Create Date: 2026-07-26 12:44:28.712014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be3a8f12f954'
down_revision: Union[str, Sequence[str], None] = 'c4a1b2d3e4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('architecture_blueprints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('use_case', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('when_to_use', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('when_not_to_use', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('use_cases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hot_spots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('complexity', sa.String(length=10), nullable=False),
    sa.Column('evolution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diagrams', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('family_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('archetype_slugs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('flows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('seed', 'user')", name='ck_architecture_blueprints_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('architecture_qualities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mechanisms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manifestations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tradeoffs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('related_technology_slugs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('related_quality_slugs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('performance', 'reliability', 'recovery', 'data-integrity', 'operability')", name='ck_architecture_qualities_category'),
    sa.CheckConstraint("source IN ('seed', 'user')", name='ck_architecture_qualities_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_architecture_qualities_category'), 'architecture_qualities', ['category'], unique=False)
    op.create_table('data_regulations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('jurisdiction', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('effective_year', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('who_is_impacted', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('penalties', sa.String(length=500), nullable=False),
    sa.Column('official_url', sa.String(length=500), nullable=False),
    sa.Column('unit_label', sa.String(length=20), nullable=False),
    sa.Column('articles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('triggering_data_classes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('related_practice_slugs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('related_technology_slugs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('privacy', 'healthcare', 'payments', 'financial', 'ai', 'resilience')", name='ck_data_regulations_category'),
    sa.CheckConstraint("region IN ('eu', 'us', 'canada', 'brazil', 'india', 'global')", name='ck_data_regulations_region'),
    sa.CheckConstraint("source IN ('seed', 'user')", name='ck_data_regulations_source'),
    sa.CheckConstraint("status IN ('in_force', 'phasing_in')", name='ck_data_regulations_status'),
    sa.CheckConstraint("unit_label IN ('article', 'section', 'requirement', 'principle')", name='ck_data_regulations_unit_label'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_data_regulations_category'), 'data_regulations', ['category'], unique=False)
    op.create_index(op.f('ix_data_regulations_region'), 'data_regulations', ['region'], unique=False)
    op.create_table('data_safety_practices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('objective', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('complexity', sa.String(length=10), nullable=False),
    sa.Column('implementation_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('satisfies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('related_technology_slugs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('related_practice_slugs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('encryption-keys', 'deidentification', 'access-control', 'data-lifecycle', 'monitoring-response')", name='ck_data_safety_practices_category'),
    sa.CheckConstraint("complexity IN ('low', 'medium', 'high')", name='ck_data_safety_practices_complexity'),
    sa.CheckConstraint("source IN ('seed', 'user')", name='ck_data_safety_practices_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_data_safety_practices_category'), 'data_safety_practices', ['category'], unique=False)
    op.create_table('modelling_strategies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.String(length=20), nullable=False),
    sa.Column('family', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('best_for', sa.String(length=300), nullable=False),
    sa.Column('pros', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('complexity', sa.String(length=10), nullable=False),
    sa.Column('origin_year', sa.Integer(), nullable=True),
    sa.Column('originator', sa.String(length=200), nullable=True),
    sa.Column('example', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diagram', sa.Text(), nullable=False),
    sa.Column('related_technology_slugs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("complexity IN ('low', 'medium', 'high')", name='ck_modelling_strategies_complexity'),
    sa.CheckConstraint("family IN ('normalization', 'warehouse-methodologies', 'dimensional-schemas', 'nosql', 'specialized', 'slowly-changing-dimensions', 'compatibility', 'migration-patterns', 'text-formats', 'binary-row-formats', 'columnar-formats')", name='ck_modelling_strategies_family'),
    sa.CheckConstraint("source IN ('seed', 'user')", name='ck_modelling_strategies_source'),
    sa.CheckConstraint("topic IN ('modelling', 'evolution', 'serialization')", name='ck_modelling_strategies_topic'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_modelling_strategies_family'), 'modelling_strategies', ['family'], unique=False)
    op.create_index(op.f('ix_modelling_strategies_topic'), 'modelling_strategies', ['topic'], unique=False)
    op.create_table('project_archetypes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('family', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('supports_greenfield', sa.Boolean(), nullable=False),
    sa.Column('supports_brownfield', sa.Boolean(), nullable=False),
    sa.Column('is_initiative', sa.Boolean(), nullable=False),
    sa.Column('typical_category_slugs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_blueprint_slugs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('seed_tier', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("family IN ('acquisition-ingestion', 'movement-migration', 'transformation-modelling', 'storage-platform', 'streaming-realtime', 'orchestration-dataops', 'governance-security-compliance', 'analytics-serving', 'ml-ai-infrastructure', 'discovery-strategy')", name='ck_project_archetypes_family'),
    sa.CheckConstraint("source IN ('seed', 'user')", name='ck_project_archetypes_source'),
    sa.CheckConstraint('seed_tier IN (1, 2, 3)', name='ck_project_archetypes_seed_tier'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_project_archetypes_family'), 'project_archetypes', ['family'], unique=False)
    op.create_table('tech_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('seed', 'user')", name='ck_tech_categories_source'),
    sa.ForeignKeyConstraint(['parent_id'], ['tech_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('technologies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('secondary_category_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('homepage_url', sa.String(length=512), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deployment_models', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('oss', sa.Boolean(), nullable=False),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.Column('maturity', sa.String(length=20), nullable=False),
    sa.Column('learning_curve', sa.String(length=20), nullable=False),
    sa.Column('time_to_win', sa.String(length=20), nullable=False),
    sa.Column('cost_model', sa.String(length=20), nullable=False),
    sa.Column('cost_tier', sa.String(length=20), nullable=False),
    sa.Column('auth_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("maturity IN ('emerging', 'established', 'legacy')", name='ck_technologies_maturity'),
    sa.CheckConstraint("source IN ('seed', 'user')", name='ck_technologies_source'),
    sa.ForeignKeyConstraint(['category_id'], ['tech_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_technologies_category_id'), 'technologies', ['category_id'], unique=False)
    op.create_table('blueprint_stages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('blueprint_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('recommended_technology_id', sa.Uuid(), nullable=True),
    sa.Column('alternative_technology_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=True),
    sa.Column('pos_y', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('custom_color', sa.String(length=32), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('owner_name', sa.String(length=160), nullable=False),
    sa.Column('owner_email', sa.String(length=254), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['architecture_blueprints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommended_technology_id'], ['technologies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blueprint_stages_blueprint_id'), 'blueprint_stages', ['blueprint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blueprint_stages_blueprint_id'), table_name='blueprint_stages')
    op.drop_table('blueprint_stages')
    op.drop_index(op.f('ix_technologies_category_id'), table_name='technologies')
    op.drop_table('technologies')
    op.drop_table('tech_categories')
    op.drop_index(op.f('ix_project_archetypes_family'), table_name='project_archetypes')
    op.drop_table('project_archetypes')
    op.drop_index(op.f('ix_modelling_strategies_topic'), table_name='modelling_strategies')
    op.drop_index(op.f('ix_modelling_strategies_family'), table_name='modelling_strategies')
    op.drop_table('modelling_strategies')
    op.drop_index(op.f('ix_data_safety_practices_category'), table_name='data_safety_practices')
    op.drop_table('data_safety_practices')
    op.drop_index(op.f('ix_data_regulations_region'), table_name='data_regulations')
    op.drop_index(op.f('ix_data_regulations_category'), table_name='data_regulations')
    op.drop_table('data_regulations')
    op.drop_index(op.f('ix_architecture_qualities_category'), table_name='architecture_qualities')
    op.drop_table('architecture_qualities')
    op.drop_table('architecture_blueprints')
    # ### end Alembic commands ###
