"""news

Revision ID: d1eb80ad5e2c
Revises: 08ed12202356
Create Date: 2026-07-16 08:06:53.596242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1eb80ad5e2c'
down_revision: Union[str, Sequence[str], None] = '08ed12202356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cadence', sa.String(length=64), server_default='daily', nullable=False),
    sa.Column('max_items_per_topic', sa.Integer(), server_default='10', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='suggested', nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=True),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_recommendations_status'), 'news_recommendations', ['status'], unique=False)
    op.create_table('news_topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('from_configured_source', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['news_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_created_at'), 'news_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_news_items_fingerprint'), 'news_items', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_news_items_read_at'), 'news_items', ['read_at'], unique=False)
    op.create_index(op.f('ix_news_items_topic_id'), 'news_items', ['topic_id'], unique=False)
    op.create_table('news_polls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('trigger', sa.String(length=16), server_default='manual', nullable=False),
    sa.Column('items_found', sa.Integer(), nullable=True),
    sa.Column('items_inserted', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['news_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_polls_topic_created', 'news_polls', ['topic_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_news_polls_topic_id'), 'news_polls', ['topic_id'], unique=False)
    op.create_table('news_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['news_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'url', name='uq_news_sources_topic_url')
    )
    op.create_index(op.f('ix_news_sources_topic_id'), 'news_sources', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_sources_topic_id'), table_name='news_sources')
    op.drop_table('news_sources')
    op.drop_index(op.f('ix_news_polls_topic_id'), table_name='news_polls')
    op.drop_index('ix_news_polls_topic_created', table_name='news_polls')
    op.drop_table('news_polls')
    op.drop_index(op.f('ix_news_items_topic_id'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_read_at'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_fingerprint'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_created_at'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_table('news_topics')
    op.drop_index(op.f('ix_news_recommendations_status'), table_name='news_recommendations')
    op.drop_table('news_recommendations')
    op.drop_table('news_config')
    # ### end Alembic commands ###
