"""roadmap drift

Revision ID: f2f01d057a8e
Revises: 803ea6d2f00c
Create Date: 2026-07-16 11:33:33.811865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f01d057a8e'
down_revision: Union[str, Sequence[str], None] = '803ea6d2f00c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_drift_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['roadmap_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_drift_checks_repository_id'), 'roadmap_drift_checks', ['repository_id'], unique=False)
    op.create_index(op.f('ix_roadmap_drift_checks_version_id'), 'roadmap_drift_checks', ['version_id'], unique=False)
    op.create_table('roadmap_drift_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('drift_check_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['drift_check_id'], ['roadmap_drift_checks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['roadmap_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_drift_findings_drift_check_id'), 'roadmap_drift_findings', ['drift_check_id'], unique=False)
    op.create_index(op.f('ix_roadmap_drift_findings_item_id'), 'roadmap_drift_findings', ['item_id'], unique=False)
    op.create_index(op.f('ix_roadmap_drift_findings_status'), 'roadmap_drift_findings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_drift_findings_status'), table_name='roadmap_drift_findings')
    op.drop_index(op.f('ix_roadmap_drift_findings_item_id'), table_name='roadmap_drift_findings')
    op.drop_index(op.f('ix_roadmap_drift_findings_drift_check_id'), table_name='roadmap_drift_findings')
    op.drop_table('roadmap_drift_findings')
    op.drop_index(op.f('ix_roadmap_drift_checks_version_id'), table_name='roadmap_drift_checks')
    op.drop_index(op.f('ix_roadmap_drift_checks_repository_id'), table_name='roadmap_drift_checks')
    op.drop_table('roadmap_drift_checks')
    # ### end Alembic commands ###
